type GenreSong = {
  name: string;
  artist: string;
  year: number;
};

export const EXTRA_GENRE_SONGS_CLASSICS = {
  'R&B': [
    { name: 'Sexual Healing', artist: 'Marvin Gaye', year: 1982 },
    { name: 'Let\'s Get It On', artist: 'Marvin Gaye', year: 1973 },
    { name: 'What\'s Going On', artist: 'Marvin Gaye', year: 1971 },
    { name: 'Ain\'t No Mountain High Enough', artist: 'Marvin Gaye & Tammi Terrell', year: 1967 },
    { name: 'Let\'s Stay Together', artist: 'Al Green', year: 1971 },
    { name: 'Tired of Being Alone', artist: 'Al Green', year: 1971 },
    { name: 'Love and Happiness', artist: 'Al Green', year: 1972 },
    { name: 'Superstition', artist: 'Stevie Wonder', year: 1972 },
    { name: 'Signed, Sealed, Delivered', artist: 'Stevie Wonder', year: 1970 },
    { name: 'Isn\'t She Lovely', artist: 'Stevie Wonder', year: 1976 },
    { name: 'I Just Called to Say I Love You', artist: 'Stevie Wonder', year: 1984 },
    { name: 'Respect', artist: 'Aretha Franklin', year: 1967 },
    { name: 'I Say a Little Prayer', artist: 'Aretha Franklin', year: 1968 },
    { name: 'Chain of Fools', artist: 'Aretha Franklin', year: 1967 },
    { name: 'Outstanding', artist: 'The Gap Band', year: 1982 },
    { name: 'You Dropped a Bomb on Me', artist: 'The Gap Band', year: 1982 },
    { name: 'Before I Let Go', artist: 'Maze & Frankie Beverly', year: 1981 },
    { name: 'Candy', artist: 'Cameo', year: 1986 },
    { name: 'Computer Love', artist: 'Zapp', year: 1985 },
    { name: 'Juicy Fruit', artist: 'Mtume', year: 1983 },
    { name: 'Sweet Love', artist: 'Anita Baker', year: 1986 },
    { name: 'Caught Up in the Rapture', artist: 'Anita Baker', year: 1986 },
    { name: 'Back at One', artist: 'Brian McKnight', year: 1999 },
    { name: 'Anytime', artist: 'Brian McKnight', year: 1997 },
    { name: 'End of the Road', artist: 'Boyz II Men', year: 1992 },
    { name: 'I\'ll Make Love to You', artist: 'Boyz II Men', year: 1994 },
    { name: 'On Bended Knee', artist: 'Boyz II Men', year: 1994 },
    { name: 'Can We Talk', artist: 'Tevin Campbell', year: 1993 },
    { name: 'Weak', artist: 'SWV', year: 1992 },
    { name: 'Right Here', artist: 'SWV', year: 1992 },
    { name: 'If You Love Me', artist: 'Brownstone', year: 1994 },
    { name: 'Don\'t Walk Away', artist: 'Jade', year: 1992 },
    { name: 'Just Kickin\' It', artist: 'Xscape', year: 1993 },
    { name: 'Understanding', artist: 'Xscape', year: 1993 },
    { name: 'Not Gon\' Cry', artist: 'Mary J. Blige', year: 1996 },
    { name: 'Family Affair', artist: 'Mary J. Blige', year: 2001 },
    { name: 'Doo Wop (That Thing)', artist: 'Lauryn Hill', year: 1998 },
    { name: 'Ex-Factor', artist: 'Lauryn Hill', year: 1998 },
    { name: 'Killing Me Softly', artist: 'Fugees', year: 1996 },
    { name: 'No Diggity', artist: 'Blackstreet', year: 1996 },
    { name: 'Pony', artist: 'Ginuwine', year: 1996 },
    { name: 'Twisted', artist: 'Keith Sweat', year: 1996 },
    { name: 'Freak Me', artist: 'Silk', year: 1992 },
    { name: 'Knockin\' Da Boots', artist: 'H-Town', year: 1993 },
    { name: 'Forever My Lady', artist: 'Jodeci', year: 1991 },
    { name: 'Come and Talk to Me', artist: 'Jodeci', year: 1991 },
    { name: 'Brown Sugar', artist: 'D\'Angelo', year: 1995 },
    { name: 'Untitled (How Does It Feel)', artist: 'D\'Angelo', year: 2000 },
    { name: 'Adorn', artist: 'Miguel', year: 2012 },
    { name: 'Sure Thing', artist: 'Miguel', year: 2010 },
    { name: 'Boo\'d Up', artist: 'Ella Mai', year: 2017 },
    { name: 'Trip', artist: 'Ella Mai', year: 2018 },
    { name: 'Focus', artist: 'H.E.R.', year: 2016 },
    { name: 'Best Part', artist: 'Daniel Caesar & H.E.R.', year: 2017 },
    { name: 'Leave the Door Open', artist: 'Silk Sonic', year: 2021 },
    { name: 'Smokin Out the Window', artist: 'Silk Sonic', year: 2021 },
    { name: 'Redbone', artist: 'Childish Gambino', year: 2016 },
    { name: 'Heartbreak Anniversary', artist: 'Giveon', year: 2020 },
    { name: 'Girls Need Love', artist: 'Summer Walker', year: 2018 },
    { name: 'Un-thinkable', artist: 'Alicia Keys', year: 2009 },
    { name: 'You Don\'t Know My Name', artist: 'Alicia Keys', year: 2003 },
    { name: 'Confessions Part II', artist: 'Usher', year: 2004 },
    { name: 'U Got It Bad', artist: 'Usher', year: 2001 },
    { name: 'Love T.K.O.', artist: 'Teddy Pendergrass', year: 1980 },
    { name: 'When Doves Cry', artist: 'Prince', year: 1984 },
    { name: 'Kiss', artist: 'Prince', year: 1986 },
    { name: 'The Most Beautiful Girl in the World', artist: 'Prince', year: 1994 },
    { name: 'Smooth Operator', artist: 'Sade', year: 1984 },
    { name: 'No Ordinary Love', artist: 'Sade', year: 1992 },
    { name: 'By Your Side', artist: 'Sade', year: 2000 },
    { name: 'Rock with You', artist: 'Michael Jackson', year: 1979 },
    { name: 'Remember the Time', artist: 'Michael Jackson', year: 1991 },
    { name: 'Human Nature', artist: 'Michael Jackson', year: 1982 },
    { name: 'I Wanna Be Down', artist: 'Brandy', year: 1994 },
    { name: 'Have You Ever', artist: 'Brandy', year: 1998 },
    { name: 'The Boy Is Mine', artist: 'Brandy & Monica', year: 1998 },
    { name: 'Before You Walk Out of My Life', artist: 'Monica', year: 1995 },
    { name: 'Angel of Mine', artist: 'Monica', year: 1998 },
    { name: 'Say My Name', artist: 'Destiny\'s Child', year: 1999 },
    { name: 'Bills, Bills, Bills', artist: 'Destiny\'s Child', year: 1999 },
    { name: 'Survivor', artist: 'Destiny\'s Child', year: 2001 },
    { name: 'Return of the Mack', artist: 'Mark Morrison', year: 1996 },
    { name: 'Rhythm of the Night', artist: 'DeBarge', year: 1985 },
    { name: 'I Like It', artist: 'DeBarge', year: 1982 },
    { name: 'Rock the Boat', artist: 'Aaliyah', year: 2001 },
    { name: 'Try Again', artist: 'Aaliyah', year: 2000 },
    { name: 'Are You That Somebody?', artist: 'Aaliyah', year: 1998 },
    { name: 'Foolish', artist: 'Ashanti', year: 2002 },
    { name: 'Rock Wit U', artist: 'Ashanti', year: 2003 },
    { name: 'All My Life', artist: 'K-Ci & JoJo', year: 1997 },
    { name: 'Tell Me It\'s Real', artist: 'K-Ci & JoJo', year: 1999 },
    { name: 'Peaches & Cream', artist: '112', year: 2001 },
    { name: 'Cupid', artist: '112', year: 1996 },
    { name: 'One in a Million', artist: 'Aaliyah', year: 1996 },
    { name: 'Differences', artist: 'Ginuwine', year: 2001 },
    { name: 'Freek\'n You', artist: 'Jodeci', year: 1995 },
    { name: 'Nobody', artist: 'Keith Sweat', year: 1996 },
    { name: 'Sweet Lady', artist: 'Tyrese', year: 1998 },
    { name: 'How You Gonna Act Like That', artist: 'Tyrese', year: 2002 },
    { name: 'Pretty Wings', artist: 'Maxwell', year: 2009 },
    { name: 'Ascension', artist: 'Maxwell', year: 1996 },
    { name: 'So Into You', artist: 'Tamia', year: 1998 },
    { name: 'Stranger in My House', artist: 'Tamia', year: 2000 },
  ],

  'Classic Hits': [
    { name: 'Imagine', artist: 'John Lennon', year: 1971 },
    { name: 'Stand by Me', artist: 'Ben E. King', year: 1961 },
    { name: 'What a Wonderful World', artist: 'Louis Armstrong', year: 1967 },
    { name: 'Respect', artist: 'Aretha Franklin', year: 1967 },
    { name: 'I Say a Little Prayer', artist: 'Aretha Franklin', year: 1968 },
    { name: 'Son of a Preacher Man', artist: 'Dusty Springfield', year: 1968 },
    { name: 'Build Me Up Buttercup', artist: 'The Foundations', year: 1968 },
    { name: 'Good Vibrations', artist: 'The Beach Boys', year: 1966 },
    { name: 'God Only Knows', artist: 'The Beach Boys', year: 1966 },
    { name: 'California Dreamin\'', artist: 'The Mamas & The Papas', year: 1965 },
    { name: 'Mrs. Robinson', artist: 'Simon & Garfunkel', year: 1968 },
    { name: 'Bridge Over Troubled Water', artist: 'Simon & Garfunkel', year: 1970 },
    { name: 'The Sound of Silence', artist: 'Simon & Garfunkel', year: 1964 },
    { name: 'I Heard It Through the Grapevine', artist: 'Marvin Gaye', year: 1968 },
    { name: 'Let\'s Stay Together', artist: 'Al Green', year: 1971 },
    { name: 'Lean on Me', artist: 'Bill Withers', year: 1972 },
    { name: 'Ain\'t No Sunshine', artist: 'Bill Withers', year: 1971 },
    { name: 'Lovely Day', artist: 'Bill Withers', year: 1977 },
    { name: 'Killing Me Softly with His Song', artist: 'Roberta Flack', year: 1973 },
    { name: 'You\'re So Vain', artist: 'Carly Simon', year: 1972 },
    { name: 'Dream On', artist: 'Aerosmith', year: 1973 },
    { name: 'Walk This Way', artist: 'Aerosmith', year: 1975 },
    { name: 'Stairway to Heaven', artist: 'Led Zeppelin', year: 1971 },
    { name: 'Whole Lotta Love', artist: 'Led Zeppelin', year: 1969 },
    { name: 'Sweet Emotion', artist: 'Aerosmith', year: 1975 },
    { name: 'More Than a Feeling', artist: 'Boston', year: 1976 },
    { name: 'Carry On Wayward Son', artist: 'Kansas', year: 1976 },
    { name: 'Dust in the Wind', artist: 'Kansas', year: 1977 },
    { name: 'Sultans of Swing', artist: 'Dire Straits', year: 1978 },
    { name: 'Money for Nothing', artist: 'Dire Straits', year: 1985 },
    { name: 'Wish You Were Here', artist: 'Pink Floyd', year: 1975 },
    { name: 'Another Brick in the Wall', artist: 'Pink Floyd', year: 1979 },
    { name: 'Comfortably Numb', artist: 'Pink Floyd', year: 1979 },
    { name: 'Smoke on the Water', artist: 'Deep Purple', year: 1972 },
    { name: 'Highway to Hell', artist: 'AC/DC', year: 1979 },
    { name: 'Back in Black', artist: 'AC/DC', year: 1980 },
    { name: 'You Shook Me All Night Long', artist: 'AC/DC', year: 1980 },
    { name: 'Start Me Up', artist: 'The Rolling Stones', year: 1981 },
    { name: 'Paint It, Black', artist: 'The Rolling Stones', year: 1966 },
    { name: 'Gimme Shelter', artist: 'The Rolling Stones', year: 1969 },
    { name: '(I Can\'t Get No) Satisfaction', artist: 'The Rolling Stones', year: 1965 },
    { name: 'Born to Run', artist: 'Bruce Springsteen', year: 1975 },
    { name: 'Dancing in the Dark', artist: 'Bruce Springsteen', year: 1984 },
    { name: 'Born in the U.S.A.', artist: 'Bruce Springsteen', year: 1984 },
    { name: 'Free Fallin\'', artist: 'Tom Petty', year: 1989 },
    { name: 'American Girl', artist: 'Tom Petty and the Heartbreakers', year: 1976 },
    { name: 'Take Me Home, Country Roads', artist: 'John Denver', year: 1971 },
    { name: 'Jolene', artist: 'Dolly Parton', year: 1973 },
    { name: '9 to 5', artist: 'Dolly Parton', year: 1980 },
    { name: 'Ring of Fire', artist: 'Johnny Cash', year: 1963 },
    { name: 'Sweet Dreams (Are Made of This)', artist: 'Eurythmics', year: 1983 },
    { name: 'Everybody Wants to Rule the World', artist: 'Tears for Fears', year: 1985 },
    { name: 'Wake Me Up Before You Go-Go', artist: 'Wham!', year: 1984 },
    { name: 'Faith', artist: 'George Michael', year: 1987 },
    { name: 'Time After Time', artist: 'Cyndi Lauper', year: 1983 },
    { name: 'True Colors', artist: 'Cyndi Lauper', year: 1986 },
    { name: 'Material Girl', artist: 'Madonna', year: 1984 },
    { name: 'Like a Virgin', artist: 'Madonna', year: 1984 },
    { name: 'Kiss', artist: 'Prince', year: 1986 },
    { name: 'When Doves Cry', artist: 'Prince', year: 1984 },
    { name: 'Saving All My Love for You', artist: 'Whitney Houston', year: 1985 },
    { name: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper', year: 1983 },
    { name: 'In the Air Tonight', artist: 'Phil Collins', year: 1981 },
    { name: 'Against All Odds', artist: 'Phil Collins', year: 1984 },
    { name: 'Another Day in Paradise', artist: 'Phil Collins', year: 1989 },
    { name: 'I Want to Know What Love Is', artist: 'Foreigner', year: 1984 },
    { name: 'Eye of the Tiger', artist: 'Survivor', year: 1982 },
    { name: 'Jump', artist: 'Van Halen', year: 1984 },
    { name: 'Open Arms', artist: 'Journey', year: 1981 },
    { name: 'You Make My Dreams', artist: 'Hall & Oates', year: 1980 },
    { name: 'Maneater', artist: 'Hall & Oates', year: 1982 },
    { name: 'Red Red Wine', artist: 'UB40', year: 1983 },
    { name: 'All Night Long', artist: 'Lionel Richie', year: 1983 },
    { name: 'Hello', artist: 'Lionel Richie', year: 1984 },
    { name: 'Let\'s Groove', artist: 'Earth, Wind & Fire', year: 1981 },
    { name: 'No Woman, No Cry', artist: 'Bob Marley & The Wailers', year: 1974 },
    { name: 'Three Little Birds', artist: 'Bob Marley & The Wailers', year: 1977 },
    { name: 'One Love', artist: 'Bob Marley & The Wailers', year: 1977 },
    { name: 'With or Without You', artist: 'U2', year: 1987 },
    { name: 'Where the Streets Have No Name', artist: 'U2', year: 1987 },
    { name: 'Losing My Religion', artist: 'R.E.M.', year: 1991 },
    { name: 'Wonderwall', artist: 'Oasis', year: 1995 },
    { name: 'Don\'t Look Back in Anger', artist: 'Oasis', year: 1995 },
    { name: 'Smells Like Teen Spirit', artist: 'Nirvana', year: 1991 },
    { name: 'Creep', artist: 'Radiohead', year: 1992 },
    { name: 'Don\'t Speak', artist: 'No Doubt', year: 1995 },
    { name: 'Zombie', artist: 'The Cranberries', year: 1994 },
    { name: 'Iris', artist: 'Goo Goo Dolls', year: 1998 },
  ],

  '90s Hits': [
    { name: 'Vogue', artist: 'Madonna', year: 1990 },
    { name: 'Ray of Light', artist: 'Madonna', year: 1998 },
    { name: 'Black or White', artist: 'Michael Jackson', year: 1991 },
    { name: 'Remember the Time', artist: 'Michael Jackson', year: 1991 },
    { name: 'You Are Not Alone', artist: 'Michael Jackson', year: 1995 },
    { name: 'Genie in a Bottle', artist: 'Christina Aguilera', year: 1999 },
    { name: 'What a Girl Wants', artist: 'Christina Aguilera', year: 1999 },
    { name: 'Livin\' la Vida Loca', artist: 'Ricky Martin', year: 1999 },
    { name: 'She Bangs', artist: 'Ricky Martin', year: 2000 },
    { name: 'Mambo No. 5', artist: 'Lou Bega', year: 1999 },
    { name: 'Blue (Da Ba Dee)', artist: 'Eiffel 65', year: 1998 },
    { name: 'Believe', artist: 'Cher', year: 1998 },
    { name: 'The Sign', artist: 'Ace of Base', year: 1993 },
    { name: 'All That She Wants', artist: 'Ace of Base', year: 1992 },
    { name: 'Torn', artist: 'Natalie Imbruglia', year: 1997 },
    { name: 'Un-Break My Heart', artist: 'Toni Braxton', year: 1996 },
    { name: 'This Is How We Do It', artist: 'Montell Jordan', year: 1995 },
    { name: 'Regulate', artist: 'Warren G', year: 1994 },
    { name: 'Gangsta\'s Paradise', artist: 'Coolio', year: 1995 },
    { name: 'California Love', artist: '2Pac', year: 1995 },
    { name: 'Changes', artist: '2Pac', year: 1998 },
    { name: 'Hypnotize', artist: 'The Notorious B.I.G.', year: 1997 },
    { name: 'Mo Money Mo Problems', artist: 'The Notorious B.I.G.', year: 1997 },
    { name: 'Juicy', artist: 'The Notorious B.I.G.', year: 1994 },
    { name: 'Jump Around', artist: 'House of Pain', year: 1992 },
    { name: 'Insane in the Brain', artist: 'Cypress Hill', year: 1993 },
    { name: 'Intergalactic', artist: 'Beastie Boys', year: 1998 },
    { name: 'Sabotage', artist: 'Beastie Boys', year: 1994 },
    { name: 'C.R.E.A.M.', artist: 'Wu-Tang Clan', year: 1993 },
    { name: 'Can I Kick It?', artist: 'A Tribe Called Quest', year: 1990 },
    { name: 'O.P.P.', artist: 'Naughty by Nature', year: 1991 },
    { name: 'Hip Hop Hooray', artist: 'Naughty by Nature', year: 1992 },
    { name: 'Shoop', artist: 'Salt-N-Pepa', year: 1993 },
    { name: 'Whatta Man', artist: 'Salt-N-Pepa', year: 1993 },
    { name: 'Baby Got Back', artist: 'Sir Mix-A-Lot', year: 1992 },
    { name: 'Whoomp! (There It Is)', artist: 'Tag Team', year: 1993 },
    { name: 'Gonna Make You Sweat', artist: 'C+C Music Factory', year: 1990 },
    { name: 'Rhythm Is a Dancer', artist: 'Snap!', year: 1992 },
    { name: 'What Is Love', artist: 'Haddaway', year: 1993 },
    { name: 'Be My Lover', artist: 'La Bouche', year: 1995 },
    { name: 'Another Night', artist: 'Real McCoy', year: 1993 },
    { name: 'The Rhythm of the Night', artist: 'Corona', year: 1993 },
    { name: 'Show Me Love', artist: 'Robin S.', year: 1990 },
    { name: 'Finally', artist: 'CeCe Peniston', year: 1991 },
    { name: 'Groove Is in the Heart', artist: 'Deee-Lite', year: 1990 },
    { name: 'Around the World', artist: 'Daft Punk', year: 1997 },
    { name: 'Praise You', artist: 'Fatboy Slim', year: 1998 },
    { name: 'Firestarter', artist: 'The Prodigy', year: 1996 },
    { name: 'Song 2', artist: 'Blur', year: 1997 },
    { name: 'Bitter Sweet Symphony', artist: 'The Verve', year: 1997 },
    { name: 'Tubthumping', artist: 'Chumbawamba', year: 1997 },
    { name: 'Semi-Charmed Life', artist: 'Third Eye Blind', year: 1997 },
    { name: 'Jumper', artist: 'Third Eye Blind', year: 1997 },
    { name: 'Two Princes', artist: 'Spin Doctors', year: 1991 },
    { name: 'One Week', artist: 'Barenaked Ladies', year: 1998 },
    { name: 'You Get What You Give', artist: 'New Radicals', year: 1998 },
    { name: 'Breakfast at Tiffany\'s', artist: 'Deep Blue Something', year: 1995 },
    { name: 'Closing Time', artist: 'Semisonic', year: 1998 },
    { name: 'Inside Out', artist: 'Eve 6', year: 1998 },
    { name: 'All Star', artist: 'Smash Mouth', year: 1999 },
    { name: 'Walkin\' on the Sun', artist: 'Smash Mouth', year: 1997 },
    { name: 'Santeria', artist: 'Sublime', year: 1996 },
    { name: 'What I Got', artist: 'Sublime', year: 1996 },
    { name: 'Fly', artist: 'Sugar Ray', year: 1997 },
    { name: 'Every Morning', artist: 'Sugar Ray', year: 1998 },
    { name: 'Iris', artist: 'Goo Goo Dolls', year: 1998 },
    { name: 'Slide', artist: 'Goo Goo Dolls', year: 1998 },
    { name: '3AM', artist: 'Matchbox Twenty', year: 1996 },
    { name: 'Push', artist: 'Matchbox Twenty', year: 1996 },
    { name: 'Mr. Jones', artist: 'Counting Crows', year: 1993 },
    { name: 'Run-Around', artist: 'Blues Traveler', year: 1994 },
    { name: 'One', artist: 'U2', year: 1991 },
    { name: 'Under the Bridge', artist: 'Red Hot Chili Peppers', year: 1991 },
    { name: 'Loser', artist: 'Beck', year: 1993 },
    { name: 'No Rain', artist: 'Blind Melon', year: 1992 },
    { name: 'Cannonball', artist: 'The Breeders', year: 1993 },
    { name: 'Buddy Holly', artist: 'Weezer', year: 1994 },
    { name: 'Say It Ain\'t So', artist: 'Weezer', year: 1994 },
    { name: '1979', artist: 'The Smashing Pumpkins', year: 1995 },
    { name: 'Bullet with Butterfly Wings', artist: 'The Smashing Pumpkins', year: 1995 },
    { name: 'Everlong', artist: 'Foo Fighters', year: 1997 },
    { name: 'Learn to Fly', artist: 'Foo Fighters', year: 1999 },
    { name: 'All the Small Things', artist: 'Blink-182', year: 1999 },
    { name: 'What\'s My Age Again?', artist: 'Blink-182', year: 1999 },
    { name: 'My Own Worst Enemy', artist: 'Lit', year: 1999 },
    { name: 'The Impression That I Get', artist: 'The Mighty Mighty Bosstones', year: 1997 },
    { name: 'Flagpole Sitta', artist: 'Harvey Danger', year: 1997 },
    { name: 'Peaches', artist: 'The Presidents of the United States of America', year: 1995 },
    { name: 'Kiss Me', artist: 'Sixpence None the Richer', year: 1998 },
    { name: 'I Don\'t Want to Wait', artist: 'Paula Cole', year: 1996 },
    { name: 'Criminal', artist: 'Fiona Apple', year: 1996 },
    { name: 'You Were Meant for Me', artist: 'Jewel', year: 1995 },
    { name: 'Save Tonight', artist: 'Eagle-Eye Cherry', year: 1997 },
    { name: 'How Bizarre', artist: 'OMC', year: 1995 },
    { name: 'Cotton Eye Joe', artist: 'Rednex', year: 1994 },
    { name: 'Macarena', artist: 'Los Del Río', year: 1993 },
    { name: 'Virtual Insanity', artist: 'Jamiroquai', year: 1996 },
    { name: 'You Gotta Be', artist: 'Des\'ree', year: 1994 },
    { name: 'Stay', artist: 'Lisa Loeb', year: 1994 },
    { name: 'Missing', artist: 'Everything But The Girl', year: 1994 },
    { name: 'I Love You Always Forever', artist: 'Donna Lewis', year: 1996 },
    { name: 'I\'ll Be', artist: 'Edwin McCain', year: 1997 },
    { name: 'The Freshmen', artist: 'The Verve Pipe', year: 1996 },
  ],
} satisfies Record<string, GenreSong[]>;
