type GenreSong = {
  name: string;
  artist: string;
  year: number;
};

export const EXTRA_GENRE_SONGS_PARTY = {
  '2010s Hits': [
    { name: 'We Found Love', artist: 'Rihanna', year: 2011 },
    { name: 'Diamonds', artist: 'Rihanna', year: 2012 },
    { name: 'Stay', artist: 'Rihanna', year: 2012 },
    { name: 'Only Girl (In the World)', artist: 'Rihanna', year: 2010 },
    { name: 'Love the Way You Lie', artist: 'Eminem & Rihanna', year: 2010 },
    { name: 'The Monster', artist: 'Eminem & Rihanna', year: 2013 },
    { name: 'Not Afraid', artist: 'Eminem', year: 2010 },
    { name: 'Love Yourself', artist: 'Justin Bieber', year: 2015 },
    { name: 'What Do You Mean?', artist: 'Justin Bieber', year: 2015 },
    { name: 'Where Are U Now', artist: 'Skrillex & Diplo', year: 2015 },
    { name: 'Despacito', artist: 'Luis Fonsi & Daddy Yankee', year: 2017 },
    { name: 'Mi Gente', artist: 'J Balvin & Willy William', year: 2017 },
    { name: 'Havana', artist: 'Camila Cabello', year: 2017 },
    { name: 'Bad Things', artist: 'Machine Gun Kelly & Camila Cabello', year: 2016 },
    { name: 'Meant to Be', artist: 'Bebe Rexha & Florida Georgia Line', year: 2017 },
    { name: 'Stay', artist: 'Zedd & Alessia Cara', year: 2017 },
    { name: 'The Middle', artist: 'Zedd, Maren Morris & Grey', year: 2018 },
    { name: 'Bang Bang', artist: 'Jessie J, Ariana Grande & Nicki Minaj', year: 2014 },
    { name: 'Problem', artist: 'Ariana Grande', year: 2014 },
    { name: 'Break Free', artist: 'Ariana Grande & Zedd', year: 2014 },
    { name: 'Side to Side', artist: 'Ariana Grande & Nicki Minaj', year: 2016 },
    { name: 'Dangerous Woman', artist: 'Ariana Grande', year: 2016 },
    { name: 'No Tears Left to Cry', artist: 'Ariana Grande', year: 2018 },
    { name: 'Into You', artist: 'Ariana Grande', year: 2016 },
    { name: 'Cool for the Summer', artist: 'Demi Lovato', year: 2015 },
    { name: 'Sorry Not Sorry', artist: 'Demi Lovato', year: 2017 },
    { name: 'Heart Attack', artist: 'Demi Lovato', year: 2013 },
    { name: 'Wrecking Ball', artist: 'Miley Cyrus', year: 2013 },
    { name: 'We Can\'t Stop', artist: 'Miley Cyrus', year: 2013 },
    { name: 'Malibu', artist: 'Miley Cyrus', year: 2017 },
    { name: 'All About That Bass', artist: 'Meghan Trainor', year: 2014 },
    { name: 'Lips Are Movin', artist: 'Meghan Trainor', year: 2014 },
    { name: 'No', artist: 'Meghan Trainor', year: 2016 },
    { name: 'We Are Young', artist: 'fun.', year: 2011 },
    { name: 'Some Nights', artist: 'fun.', year: 2012 },
    { name: 'Ho Hey', artist: 'The Lumineers', year: 2012 },
    { name: 'Pompeii', artist: 'Bastille', year: 2013 },
    { name: 'Rude', artist: 'MAGIC!', year: 2013 },
    { name: 'Closer', artist: 'The Chainsmokers & Halsey', year: 2016 },
    { name: 'Don\'t Let Me Down', artist: 'The Chainsmokers', year: 2016 },
    { name: 'Something Just Like This', artist: 'The Chainsmokers & Coldplay', year: 2017 },
    { name: 'Paris', artist: 'The Chainsmokers', year: 2017 },
    { name: 'Lean On', artist: 'Major Lazer & DJ Snake', year: 2015 },
    { name: 'Cold Water', artist: 'Major Lazer', year: 2016 },
    { name: 'Titanium', artist: 'David Guetta & Sia', year: 2011 },
    { name: 'Hey Mama', artist: 'David Guetta', year: 2014 },
    { name: 'Play Hard', artist: 'David Guetta', year: 2012 },
    { name: 'This Is What You Came For', artist: 'Calvin Harris & Rihanna', year: 2016 },
    { name: 'Feel So Close', artist: 'Calvin Harris', year: 2012 },
    { name: 'Summer', artist: 'Calvin Harris', year: 2014 },
    { name: 'Sweet Nothing', artist: 'Calvin Harris', year: 2012 },
    { name: 'I Need Your Love', artist: 'Calvin Harris & Ellie Goulding', year: 2012 },
    { name: 'Wake Me Up', artist: 'Avicii', year: 2013 },
    { name: 'Hey Brother', artist: 'Avicii', year: 2013 },
    { name: 'The Nights', artist: 'Avicii', year: 2014 },
    { name: 'Waiting for Love', artist: 'Avicii', year: 2015 },
    { name: 'Animals', artist: 'Martin Garrix', year: 2013 },
    { name: 'In the Name of Love', artist: 'Martin Garrix & Bebe Rexha', year: 2016 },
    { name: 'Rather Be', artist: 'Clean Bandit', year: 2014 },
    { name: 'Rockabye', artist: 'Clean Bandit', year: 2016 },
    { name: 'Latch', artist: 'Disclosure & Sam Smith', year: 2012 },
    { name: 'La La La', artist: 'Naughty Boy & Sam Smith', year: 2013 },
    { name: 'Stay with Me', artist: 'Sam Smith', year: 2014 },
    { name: 'I\'m Not the Only One', artist: 'Sam Smith', year: 2014 },
    { name: 'All of Me', artist: 'John Legend', year: 2013 },
    { name: 'Riptide', artist: 'Vance Joy', year: 2013 },
    { name: 'Say You Won\'t Let Go', artist: 'James Arthur', year: 2016 },
    { name: 'Let Her Go', artist: 'Passenger', year: 2012 },
    { name: 'Budapest', artist: 'George Ezra', year: 2013 },
    { name: 'Cheerleader', artist: 'OMI', year: 2014 },
    { name: 'Stitches', artist: 'Shawn Mendes', year: 2015 },
    { name: 'Treat You Better', artist: 'Shawn Mendes', year: 2016 },
    { name: 'Attention', artist: 'Charlie Puth', year: 2017 },
    { name: 'We Don\'t Talk Anymore', artist: 'Charlie Puth & Selena Gomez', year: 2016 },
    { name: 'Faded', artist: 'Alan Walker', year: 2015 },
    { name: 'Alone', artist: 'Alan Walker', year: 2016 },
    { name: 'Let Me Love You', artist: 'DJ Snake & Justin Bieber', year: 2016 },
    { name: 'Starving', artist: 'Hailee Steinfeld & Grey', year: 2016 },
    { name: 'Burn', artist: 'Ellie Goulding', year: 2013 },
    { name: 'Love Me Like You Do', artist: 'Ellie Goulding', year: 2015 },
    { name: 'Lights', artist: 'Ellie Goulding', year: 2010 },
    { name: 'Want U Back', artist: 'Cher Lloyd', year: 2012 },
    { name: 'Wings', artist: 'Little Mix', year: 2012 },
    { name: 'Black Magic', artist: 'Little Mix', year: 2015 },
    { name: 'Cake by the Ocean', artist: 'DNCE', year: 2015 },
    { name: 'Sucker', artist: 'Jonas Brothers', year: 2019 },
    { name: 'Shut Up and Dance', artist: 'WALK THE MOON', year: 2014 },
    { name: 'Geronimo', artist: 'Sheppard', year: 2014 },
    { name: 'Habits (Stay High)', artist: 'Tove Lo', year: 2013 },
    { name: 'Talking Body', artist: 'Tove Lo', year: 2014 },
    { name: 'Jealous', artist: 'Nick Jonas', year: 2014 },
    { name: 'Ex\'s & Oh\'s', artist: 'Elle King', year: 2014 },
    { name: 'Fight Song', artist: 'Rachel Platten', year: 2015 },
    { name: 'Scars to Your Beautiful', artist: 'Alessia Cara', year: 2015 },
    { name: 'Here', artist: 'Alessia Cara', year: 2015 },
    { name: 'Pillowtalk', artist: 'Zayn', year: 2016 },
    { name: 'Girls Like You', artist: 'Maroon 5', year: 2018 },
    { name: 'Sugar', artist: 'Maroon 5', year: 2014 },
    { name: 'Love Me Again', artist: 'John Newman', year: 2013 },
  ],

  'Fiesta / Party': [
    { name: 'DJ Got Us Fallin\' in Love', artist: 'Usher', year: 2010 },
    { name: 'Scream', artist: 'Usher', year: 2012 },
    { name: 'OMG', artist: 'Usher', year: 2010 },
    { name: 'Yeah!', artist: 'Usher', year: 2004 },
    { name: 'Low', artist: 'Flo Rida', year: 2007 },
    { name: 'Wild Ones', artist: 'Flo Rida', year: 2011 },
    { name: 'Where Them Girls At', artist: 'David Guetta', year: 2011 },
    { name: 'Sexy Bitch', artist: 'David Guetta', year: 2009 },
    { name: 'Memories', artist: 'David Guetta', year: 2009 },
    { name: 'The Time (Dirty Bit)', artist: 'Black Eyed Peas', year: 2010 },
    { name: 'Let\'s Get It Started', artist: 'Black Eyed Peas', year: 2003 },
    { name: 'Pump It', artist: 'Black Eyed Peas', year: 2005 },
    { name: 'Time of Our Lives', artist: 'Pitbull', year: 2014 },
    { name: 'Hotel Room Service', artist: 'Pitbull', year: 2009 },
    { name: 'Culo', artist: 'Pitbull', year: 2004 },
    { name: 'Fireball', artist: 'Pitbull', year: 2014 },
    { name: 'We R Who We R', artist: 'Kesha', year: 2010 },
    { name: 'Tik Tok', artist: 'Kesha', year: 2009 },
    { name: 'Die Young', artist: 'Kesha', year: 2012 },
    { name: 'Blow', artist: 'Kesha', year: 2010 },
    { name: 'Turn Down for What', artist: 'DJ Snake & Lil Jon', year: 2013 },
    { name: 'Get Low', artist: 'Dillon Francis & DJ Snake', year: 2014 },
    { name: 'Lean Back', artist: 'Terror Squad', year: 2004 },
    { name: 'Get Low', artist: 'Lil Jon & The East Side Boyz', year: 2002 },
    { name: 'Shots', artist: 'Lil Jon', year: 2009 },
    { name: 'Yeah 3x', artist: 'Chris Brown', year: 2010 },
    { name: 'Turn Up the Music', artist: 'Chris Brown', year: 2012 },
    { name: 'Scream & Shout', artist: 'will.i.am & Britney Spears', year: 2012 },
    { name: '4 Minutes', artist: 'Madonna', year: 2008 },
    { name: 'Pon de Replay', artist: 'Rihanna', year: 2005 },
    { name: 'Please Don\'t Stop the Music', artist: 'Rihanna', year: 2007 },
    { name: 'We Found Love', artist: 'Rihanna', year: 2011 },
    { name: 'Get Busy', artist: 'Sean Paul', year: 2002 },
    { name: 'Like Glue', artist: 'Sean Paul', year: 2002 },
    { name: 'Danza Kuduro', artist: 'Don Omar & Lucenzo', year: 2010 },
    { name: 'Dile', artist: 'Don Omar', year: 2003 },
    { name: 'Dutty Love', artist: 'Don Omar', year: 2012 },
    { name: 'Dura', artist: 'Daddy Yankee', year: 2018 },
    { name: 'Rompe', artist: 'Daddy Yankee', year: 2005 },
    { name: 'Lo Que Pasó, Pasó', artist: 'Daddy Yankee', year: 2004 },
    { name: 'Oye Mi Canto', artist: 'N.O.R.E.', year: 2004 },
    { name: 'Rakata', artist: 'Wisin & Yandel', year: 2005 },
    { name: 'Abusadora', artist: 'Wisin & Yandel', year: 2009 },
    { name: 'Noche de Sexo', artist: 'Wisin & Yandel', year: 2005 },
    { name: 'Mayor Que Yo', artist: 'Baby Ranks', year: 2005 },
    { name: 'Yo Voy', artist: 'Zion & Lennox', year: 2004 },
    { name: 'El Amante', artist: 'Nicky Jam', year: 2017 },
    { name: 'El Perdón', artist: 'Nicky Jam & Enrique Iglesias', year: 2015 },
    { name: 'Travesuras', artist: 'Nicky Jam', year: 2014 },
    { name: 'Subeme La Radio', artist: 'Enrique Iglesias', year: 2017 },
    { name: 'I Like It', artist: 'Enrique Iglesias', year: 2010 },
    { name: 'Duele El Corazón', artist: 'Enrique Iglesias', year: 2016 },
    { name: 'Hasta el Amanecer', artist: 'Nicky Jam', year: 2016 },
    { name: 'Danza Kuduro', artist: 'Lucenzo', year: 2010 },
    { name: 'Bailar', artist: 'Deorro', year: 2016 },
    { name: 'Five More Hours', artist: 'Deorro & Chris Brown', year: 2015 },
    { name: 'Safari', artist: 'J Balvin', year: 2016 },
    { name: 'Ay Vamos', artist: 'J Balvin', year: 2014 },
    { name: 'Ginza', artist: 'J Balvin', year: 2015 },
    { name: 'Felices los 4', artist: 'Maluma', year: 2017 },
    { name: 'Borro Cassette', artist: 'Maluma', year: 2015 },
    { name: 'El Perdedor', artist: 'Maluma', year: 2015 },
    { name: 'Mayores', artist: 'Becky G', year: 2017 },
    { name: 'Sin Pijama', artist: 'Becky G & Natti Natasha', year: 2018 },
    { name: 'Sola', artist: 'Anuel AA', year: 2016 },
    { name: 'China', artist: 'Anuel AA', year: 2019 },
    { name: 'Calma', artist: 'Pedro Capó & Farruko', year: 2018 },
    { name: 'Danza Kuduro - Remix', artist: 'Don Omar', year: 2010 },
    { name: 'Waka Waka', artist: 'Shakira', year: 2010 },
    { name: 'Hips Don\'t Lie', artist: 'Shakira', year: 2005 },
    { name: 'Whenever, Wherever', artist: 'Shakira', year: 2001 },
    { name: 'La Tortura', artist: 'Shakira', year: 2005 },
    { name: 'La Bicicleta', artist: 'Carlos Vives & Shakira', year: 2016 },
    { name: 'Vivir Mi Vida', artist: 'Marc Anthony', year: 2013 },
    { name: 'Valió la Pena', artist: 'Marc Anthony', year: 2004 },
    { name: 'Suavemente', artist: 'Elvis Crespo', year: 1998 },
    { name: 'Tu Sonrisa', artist: 'Elvis Crespo', year: 1998 },
    { name: 'La Dueña del Swing', artist: 'Los Hermanos Rosario', year: 1995 },
    { name: 'Kulikitaka', artist: 'Toño Rosario', year: 2003 },
    { name: 'Abusadora', artist: 'Oro Solido', year: 2000 },
    { name: 'La Vaca', artist: 'Mala Fe', year: 2000 },
    { name: 'El Tiburón', artist: 'Proyecto Uno', year: 1993 },
    { name: 'Está Pegao', artist: 'Proyecto Uno', year: 1996 },
    { name: 'Mueve La Cadera', artist: 'Reel 2 Real', year: 1993 },
    { name: 'C\'mon N\' Ride It', artist: 'Quad City DJ\'s', year: 1996 },
    { name: 'Whoomp! (There It Is)', artist: 'Tag Team', year: 1993 },
    { name: 'Gonna Make You Sweat', artist: 'C+C Music Factory', year: 1990 },
    { name: 'Rhythm Is a Dancer', artist: 'Snap!', year: 1992 },
    { name: 'What Is Love', artist: 'Haddaway', year: 1993 },
    { name: 'Be My Lover', artist: 'La Bouche', year: 1995 },
    { name: 'Another Night', artist: 'Real McCoy', year: 1993 },
    { name: 'Pump Up the Jam', artist: 'Technotronic', year: 1989 },
    { name: 'Mr. Saxobeat', artist: 'Alexandra Stan', year: 2011 },
    { name: 'Stereo Love', artist: 'Edward Maya & Vika Jigulina', year: 2009 },
    { name: 'Barbra Streisand', artist: 'Duck Sauce', year: 2010 },
    { name: 'One More Time', artist: 'Daft Punk', year: 2000 },
    { name: 'Around the World', artist: 'Daft Punk', year: 1997 },
    { name: 'Blue (Da Ba Dee)', artist: 'Eiffel 65', year: 1998 },
    { name: 'Sandstorm', artist: 'Darude', year: 1999 },
    { name: 'Freed from Desire', artist: 'Gala', year: 1996 },
    { name: 'Samba de Janeiro', artist: 'Bellini', year: 1997 },
  ],

  'Hip Hop': [
    { name: 'Started from the Bottom', artist: 'Drake', year: 2013 },
    { name: 'Worst Behavior', artist: 'Drake', year: 2013 },
    { name: 'Hold On, We\'re Going Home', artist: 'Drake', year: 2013 },
    { name: 'Energy', artist: 'Drake', year: 2015 },
    { name: 'Back to Back', artist: 'Drake', year: 2015 },
    { name: 'Controlla', artist: 'Drake', year: 2016 },
    { name: 'Fake Love', artist: 'Drake', year: 2016 },
    { name: 'Passionfruit', artist: 'Drake', year: 2017 },
    { name: 'Money Trees', artist: 'Kendrick Lamar', year: 2012 },
    { name: 'Bitch, Don\'t Kill My Vibe', artist: 'Kendrick Lamar', year: 2012 },
    { name: 'DNA.', artist: 'Kendrick Lamar', year: 2017 },
    { name: 'King Kunta', artist: 'Kendrick Lamar', year: 2015 },
    { name: 'Backseat Freestyle', artist: 'Kendrick Lamar', year: 2012 },
    { name: 'm.A.A.d city', artist: 'Kendrick Lamar', year: 2012 },
    { name: 'The Monster', artist: 'Eminem', year: 2013 },
    { name: 'Berzerk', artist: 'Eminem', year: 2013 },
    { name: 'Love the Way You Lie', artist: 'Eminem', year: 2010 },
    { name: 'Mockingbird', artist: 'Eminem', year: 2004 },
    { name: 'Till I Collapse', artist: 'Eminem', year: 2002 },
    { name: 'My Name Is', artist: 'Eminem', year: 1999 },
    { name: 'Mask Off', artist: 'Future', year: 2017 },
    { name: 'March Madness', artist: 'Future', year: 2015 },
    { name: 'Where Ya At', artist: 'Future', year: 2015 },
    { name: 'Jumpman', artist: 'Drake & Future', year: 2015 },
    { name: 'XO TOUR Llif3', artist: 'Lil Uzi Vert', year: 2017 },
    { name: 'Money Longer', artist: 'Lil Uzi Vert', year: 2016 },
    { name: 'Broccoli', artist: 'DRAM', year: 2016 },
    { name: 'Panda', artist: 'Desiigner', year: 2015 },
    { name: 'Bank Account', artist: '21 Savage', year: 2017 },
    { name: 'Ric Flair Drip', artist: 'Offset & Metro Boomin', year: 2017 },
    { name: 'T-Shirt', artist: 'Migos', year: 2017 },
    { name: 'Fight Night', artist: 'Migos', year: 2014 },
    { name: 'Versace', artist: 'Migos', year: 2013 },
    { name: 'Look at Me!', artist: 'XXXTentacion', year: 2017 },
    { name: 'Moonlight', artist: 'XXXTentacion', year: 2018 },
    { name: 'Gummo', artist: '6ix9ine', year: 2017 },
    { name: 'Ransom', artist: 'Lil Tecca', year: 2019 },
    { name: 'The Race', artist: 'Tay-K', year: 2017 },
    { name: 'Caroline', artist: 'Aminé', year: 2016 },
    { name: 'iSpy', artist: 'KYLE', year: 2016 },
    { name: 'Black Beatles', artist: 'Rae Sremmurd', year: 2016 },
    { name: 'No Type', artist: 'Rae Sremmurd', year: 2014 },
    { name: 'No Flex Zone', artist: 'Rae Sremmurd', year: 2014 },
    { name: 'Crank That', artist: 'Soulja Boy', year: 2007 },
    { name: 'Trap Queen', artist: 'Fetty Wap', year: 2014 },
    { name: '679', artist: 'Fetty Wap', year: 2015 },
    { name: 'My Way', artist: 'Fetty Wap', year: 2015 },
    { name: 'Work REMIX', artist: 'A$AP Ferg', year: 2013 },
    { name: 'Plain Jane', artist: 'A$AP Ferg', year: 2017 },
    { name: 'Praise the Lord', artist: 'A$AP Rocky', year: 2018 },
    { name: 'Wild for the Night', artist: 'A$AP Rocky', year: 2013 },
    { name: 'Yonkers', artist: 'Tyler, The Creator', year: 2011 },
    { name: 'See You Again', artist: 'Tyler, The Creator', year: 2017 },
    { name: 'EARFQUAKE', artist: 'Tyler, The Creator', year: 2019 },
    { name: 'Crew', artist: 'GoldLink', year: 2016 },
    { name: 'No Role Modelz', artist: 'J. Cole', year: 2014 },
    { name: 'Wet Dreamz', artist: 'J. Cole', year: 2014 },
    { name: 'Power Trip', artist: 'J. Cole', year: 2013 },
    { name: 'Middle Child', artist: 'J. Cole', year: 2019 },
    { name: 'Work Out', artist: 'J. Cole', year: 2011 },
    { name: 'Clique', artist: 'Kanye West', year: 2012 },
    { name: 'Mercy', artist: 'Kanye West', year: 2012 },
    { name: 'All of the Lights', artist: 'Kanye West', year: 2010 },
    { name: 'Runaway', artist: 'Kanye West', year: 2010 },
    { name: 'All Falls Down', artist: 'Kanye West', year: 2004 },
    { name: 'Heartless', artist: 'Kanye West', year: 2008 },
    { name: 'Ni**as in Paris', artist: 'Jay-Z & Kanye West', year: 2011 },
    { name: 'Otis', artist: 'Jay-Z & Kanye West', year: 2011 },
    { name: 'Run This Town', artist: 'Jay-Z', year: 2009 },
    { name: 'Big Pimpin\'', artist: 'Jay-Z', year: 1999 },
    { name: 'Hard Knock Life', artist: 'Jay-Z', year: 1998 },
    { name: 'Go DJ', artist: 'Lil Wayne', year: 2004 },
    { name: 'Mrs. Officer', artist: 'Lil Wayne', year: 2008 },
    { name: 'Love Me', artist: 'Lil Wayne', year: 2013 },
    { name: 'Uproar', artist: 'Lil Wayne', year: 2018 },
    { name: 'Drip Too Hard', artist: 'Lil Baby & Gunna', year: 2018 },
    { name: 'Yes Indeed', artist: 'Lil Baby & Drake', year: 2018 },
    { name: 'Freestyle', artist: 'Lil Baby', year: 2017 },
    { name: 'Lifestyle', artist: 'Rich Gang', year: 2014 },
    { name: 'Hot', artist: 'Young Thug', year: 2019 },
    { name: 'Pick Up the Phone', artist: 'Young Thug & Travis Scott', year: 2016 },
    { name: 'No Heart', artist: '21 Savage', year: 2016 },
    { name: 'A Lot', artist: '21 Savage', year: 2018 },
    { name: 'Swimming Pools', artist: 'Kendrick Lamar', year: 2012 },
    { name: 'X Gon\' Give It To Ya', artist: 'DMX', year: 2003 },
    { name: 'Party Up', artist: 'DMX', year: 1999 },
    { name: 'Still D.R.E.', artist: 'Dr. Dre', year: 1999 },
    { name: 'Forgot About Dre', artist: 'Dr. Dre', year: 1999 },
    { name: 'California Love', artist: '2Pac', year: 1995 },
    { name: 'Changes', artist: '2Pac', year: 1998 },
    { name: 'Hypnotize', artist: 'The Notorious B.I.G.', year: 1997 },
    { name: 'Juicy', artist: 'The Notorious B.I.G.', year: 1994 },
    { name: 'Mo Money Mo Problems', artist: 'The Notorious B.I.G.', year: 1997 },
    { name: 'N.Y. State of Mind', artist: 'Nas', year: 1994 },
    { name: 'If I Ruled the World', artist: 'Nas', year: 1996 },
    { name: 'Made You Look', artist: 'Nas', year: 2002 },
    { name: 'The World Is Yours', artist: 'Nas', year: 1994 },
    { name: 'Lean Back', artist: 'Terror Squad', year: 2004 },
    { name: 'Hate It or Love It', artist: 'The Game', year: 2005 },
    { name: 'Ms. Jackson', artist: 'OutKast', year: 2000 },
    { name: 'Hey Ya!', artist: 'OutKast', year: 2003 },
    { name: 'Roses', artist: 'OutKast', year: 2003 },
    { name: 'Drop It Like It\'s Hot', artist: 'Snoop Dogg', year: 2004 },
  ],
} satisfies Record<string, GenreSong[]>;
