type GenreSong = {
  name: string;
  artist: string;
  year: number;
};

export const EXTRA_GENRE_SONGS_POP = {
  'Rock en Español': [
    { name: 'Mariposa Traicionera', artist: 'Maná', year: 2002 },
    { name: 'Vivir Sin Aire', artist: 'Maná', year: 1992 },
    { name: 'Te Lloré un Río', artist: 'Maná', year: 1992 },
    { name: 'Manda Una Señal', artist: 'Maná', year: 2006 },
    { name: 'Bendita Tu Luz', artist: 'Maná', year: 2006 },
    { name: 'Ángel de Amor', artist: 'Maná', year: 2002 },
    { name: 'Hechicera', artist: 'Maná', year: 1997 },
    { name: 'Signos', artist: 'Soda Stereo', year: 1986 },
    { name: 'Trátame Suavemente', artist: 'Soda Stereo', year: 1984 },
    { name: 'Juegos de Seducción', artist: 'Soda Stereo', year: 1985 },
    { name: 'Zoom', artist: 'Soda Stereo', year: 1995 },
    { name: 'Un Millón de Años Luz', artist: 'Soda Stereo', year: 1990 },
    { name: 'Prófugos', artist: 'Soda Stereo', year: 1986 },
    { name: 'Sobredosis de TV', artist: 'Soda Stereo', year: 1984 },
    { name: 'Cuando Pase el Temblor', artist: 'Soda Stereo', year: 1985 },
    { name: 'Crimen', artist: 'Gustavo Cerati', year: 2006 },
    { name: 'Puente', artist: 'Gustavo Cerati', year: 1999 },
    { name: 'Adiós', artist: 'Gustavo Cerati', year: 2006 },
    { name: 'Lago en el Cielo', artist: 'Gustavo Cerati', year: 2006 },
    { name: 'Deja Vu', artist: 'Gustavo Cerati', year: 2009 },
    { name: 'La Negra Tomasa', artist: 'Caifanes', year: 1988 },
    { name: 'Afuera', artist: 'Caifanes', year: 1994 },
    { name: 'Viento', artist: 'Caifanes', year: 1992 },
    { name: 'No Dejes Que', artist: 'Caifanes', year: 1992 },
    { name: 'Nubes', artist: 'Caifanes', year: 1992 },
    { name: 'Mátenme Porque Me Muero', artist: 'Caifanes', year: 1988 },
    { name: 'La Célula Que Explota', artist: 'Caifanes', year: 1990 },
    { name: 'Entre Dos Tierras', artist: 'Héroes del Silencio', year: 1990 },
    { name: 'Maldito Duende', artist: 'Héroes del Silencio', year: 1990 },
    { name: 'La Chispa Adecuada', artist: 'Héroes del Silencio', year: 1995 },
    { name: 'Avalancha', artist: 'Héroes del Silencio', year: 1995 },
    { name: 'Flor Venenosa', artist: 'Héroes del Silencio', year: 1993 },
    { name: 'Tu Cárcel', artist: 'Los Enanitos Verdes', year: 1986 },
    { name: 'La Muralla Verde', artist: 'Los Enanitos Verdes', year: 1986 },
    { name: 'Guitarras Blancas', artist: 'Los Enanitos Verdes', year: 1988 },
    { name: 'Te Vi En Un Tren', artist: 'Los Enanitos Verdes', year: 1987 },
    { name: 'Luz de Día', artist: 'Los Enanitos Verdes', year: 1996 },
    { name: 'Mi Primer Día Sin Ti', artist: 'Los Enanitos Verdes', year: 1999 },
    { name: 'Igual Que Ayer', artist: 'Los Enanitos Verdes', year: 1992 },
    { name: 'Devuélveme a Mi Chica', artist: 'Hombres G', year: 1985 },
    { name: 'Marta Tiene un Marcapasos', artist: 'Hombres G', year: 1986 },
    { name: 'Venezia', artist: 'Hombres G', year: 1985 },
    { name: 'Te Quiero', artist: 'Hombres G', year: 1986 },
    { name: 'El Ataque de las Chicas Cocodrilo', artist: 'Hombres G', year: 1986 },
    { name: 'En Algún Lugar', artist: 'Duncan Dhu', year: 1987 },
    { name: 'Cien Gaviotas', artist: 'Duncan Dhu', year: 1986 },
    { name: 'Una Calle de París', artist: 'Duncan Dhu', year: 1988 },
    { name: 'Lucha de Gigantes', artist: 'Nacha Pop', year: 1987 },
    { name: 'La Chica de Ayer', artist: 'Nacha Pop', year: 1980 },
    { name: 'Escuela de Calor', artist: 'Radio Futura', year: 1984 },
    { name: 'Veneno en la Piel', artist: 'Radio Futura', year: 1990 },
    { name: 'Enamorado de la Moda Juvenil', artist: 'Radio Futura', year: 1980 },
    { name: 'Cuando Seas Grande', artist: 'Miguel Mateos', year: 1986 },
    { name: 'Obsesión', artist: 'Miguel Mateos', year: 1990 },
    { name: 'Atado a un Sentimiento', artist: 'Miguel Mateos', year: 1987 },
    { name: 'Nos Siguen Pegando Abajo', artist: 'Charly García', year: 1983 },
    { name: 'No Voy en Tren', artist: 'Charly García', year: 1987 },
    { name: 'Demoliendo Hoteles', artist: 'Charly García', year: 1984 },
    { name: 'Los Dinosaurios', artist: 'Charly García', year: 1983 },
    { name: 'Mariposa Tecknicolor', artist: 'Fito Páez', year: 1994 },
    { name: 'El Amor Después del Amor', artist: 'Fito Páez', year: 1992 },
    { name: 'Al Lado del Camino', artist: 'Fito Páez', year: 1999 },
    { name: 'Tumbas de la Gloria', artist: 'Fito Páez', year: 1992 },
    { name: 'Dar es Dar', artist: 'Fito Páez', year: 1996 },
    { name: 'A Rodar Mi Vida', artist: 'Fito Páez', year: 1992 },
    { name: 'Flaca', artist: 'Andrés Calamaro', year: 1997 },
    { name: 'Paloma', artist: 'Andrés Calamaro', year: 1999 },
    { name: 'Los Aviones', artist: 'Andrés Calamaro', year: 1999 },
    { name: 'Te Quiero Igual', artist: 'Andrés Calamaro', year: 1999 },
    { name: 'Crímenes Perfectos', artist: 'Andrés Calamaro', year: 1997 },
    { name: 'Sin Documentos', artist: 'Los Rodríguez', year: 1993 },
    { name: 'Dulce Condena', artist: 'Los Rodríguez', year: 1995 },
    { name: 'Tren al Sur', artist: 'Los Prisioneros', year: 1990 },
    { name: 'Estrechez de Corazón', artist: 'Los Prisioneros', year: 1990 },
    { name: 'El Baile de los Que Sobran', artist: 'Los Prisioneros', year: 1986 },
    { name: 'Paramar', artist: 'Los Prisioneros', year: 1986 },
    { name: 'Bolero Falaz', artist: 'Aterciopelados', year: 1995 },
    { name: 'Florecita Rockera', artist: 'Aterciopelados', year: 1995 },
    { name: 'Baracunatana', artist: 'Aterciopelados', year: 1996 },
    { name: 'El Estuche', artist: 'Aterciopelados', year: 1997 },
    { name: 'Ingrata', artist: 'Café Tacvba', year: 1994 },
    { name: 'Chilanga Banda', artist: 'Café Tacvba', year: 1996 },
    { name: 'El Baile y el Salón', artist: 'Café Tacvba', year: 1994 },
    { name: 'Como Te Extraño Mi Amor', artist: 'Café Tacvba', year: 1996 },
    { name: 'Quiero Ver', artist: 'Café Tacvba', year: 2007 },
    { name: 'Volver a Comenzar', artist: 'Café Tacvba', year: 2007 },
    { name: 'Puto', artist: 'Molotov', year: 1997 },
    { name: 'Voto Latino', artist: 'Molotov', year: 1997 },
    { name: 'Here We Kum', artist: 'Molotov', year: 2004 },
    { name: 'Pachuco', artist: 'Maldita Vecindad', year: 1991 },
    { name: 'Kumbala', artist: 'Maldita Vecindad', year: 1991 },
    { name: 'Un Gran Circo', artist: 'Maldita Vecindad', year: 1991 },
    { name: 'Vasos Vacíos', artist: 'Los Fabulosos Cadillacs', year: 1993 },
    { name: 'Siguiendo la Luna', artist: 'Los Fabulosos Cadillacs', year: 1992 },
    { name: 'Mal Bicho', artist: 'Los Fabulosos Cadillacs', year: 1995 },
    { name: 'Calaveras y Diablitos', artist: 'Los Fabulosos Cadillacs', year: 1997 },
    { name: 'Sr. Cobranza', artist: 'Bersuit Vergarabat', year: 1998 },
    { name: 'Yo Tomo', artist: 'Bersuit Vergarabat', year: 1998 },
    { name: 'La Argentinidad al Palo', artist: 'Bersuit Vergarabat', year: 2004 },
    { name: 'Irresponsables', artist: 'Babasónicos', year: 2003 },
  ],

  'Pop Internacional': [
    { name: 'Billie Jean', artist: 'Michael Jackson', year: 1982 },
    { name: 'Beat It', artist: 'Michael Jackson', year: 1982 },
    { name: 'Thriller', artist: 'Michael Jackson', year: 1982 },
    { name: 'Smooth Criminal', artist: 'Michael Jackson', year: 1987 },
    { name: 'Black or White', artist: 'Michael Jackson', year: 1991 },
    { name: 'Like a Prayer', artist: 'Madonna', year: 1989 },
    { name: 'Like a Virgin', artist: 'Madonna', year: 1984 },
    { name: 'Material Girl', artist: 'Madonna', year: 1984 },
    { name: 'Vogue', artist: 'Madonna', year: 1990 },
    { name: 'Hung Up', artist: 'Madonna', year: 2005 },
    { name: 'Toxic', artist: 'Britney Spears', year: 2003 },
    { name: 'Baby One More Time', artist: 'Britney Spears', year: 1998 },
    { name: 'Oops!... I Did It Again', artist: 'Britney Spears', year: 2000 },
    { name: 'Womanizer', artist: 'Britney Spears', year: 2008 },
    { name: 'Everytime', artist: 'Britney Spears', year: 2003 },
    { name: 'Genie in a Bottle', artist: 'Christina Aguilera', year: 1999 },
    { name: 'Beautiful', artist: 'Christina Aguilera', year: 2002 },
    { name: 'Fighter', artist: 'Christina Aguilera', year: 2002 },
    { name: "Hips Don't Lie", artist: 'Shakira', year: 2005 },
    { name: 'Whenever, Wherever', artist: 'Shakira', year: 2001 },
    { name: "Can't Remember to Forget You", artist: 'Shakira', year: 2014 },
    { name: 'Love Me Like You Do', artist: 'Ellie Goulding', year: 2015 },
    { name: 'Burn', artist: 'Ellie Goulding', year: 2013 },
    { name: 'Lights', artist: 'Ellie Goulding', year: 2010 },
    { name: 'Green Light', artist: 'Lorde', year: 2017 },
    { name: 'Team', artist: 'Lorde', year: 2013 },
    { name: 'Good 4 U', artist: 'Olivia Rodrigo', year: 2021 },
    { name: 'Drivers License', artist: 'Olivia Rodrigo', year: 2021 },
    { name: 'Vampire', artist: 'Olivia Rodrigo', year: 2023 },
    { name: 'Cruel Summer', artist: 'Taylor Swift', year: 2019 },
    { name: 'Style', artist: 'Taylor Swift', year: 2014 },
    { name: 'You Belong With Me', artist: 'Taylor Swift', year: 2008 },
    { name: 'I Knew You Were Trouble', artist: 'Taylor Swift', year: 2012 },
    { name: 'We Are Never Ever Getting Back Together', artist: 'Taylor Swift', year: 2012 },
    { name: 'Cardigan', artist: 'Taylor Swift', year: 2020 },
    { name: 'Rain On Me', artist: 'Lady Gaga', year: 2020 },
    { name: 'The Edge of Glory', artist: 'Lady Gaga', year: 2011 },
    { name: 'Paparazzi', artist: 'Lady Gaga', year: 2008 },
    { name: 'Alejandro', artist: 'Lady Gaga', year: 2009 },
    { name: 'Applause', artist: 'Lady Gaga', year: 2013 },
    { name: 'Telephone', artist: 'Lady Gaga', year: 2009 },
    { name: 'California Gurls', artist: 'Katy Perry', year: 2010 },
    { name: 'Last Friday Night', artist: 'Katy Perry', year: 2010 },
    { name: 'E.T.', artist: 'Katy Perry', year: 2010 },
    { name: 'Hot N Cold', artist: 'Katy Perry', year: 2008 },
    { name: 'I Kissed a Girl', artist: 'Katy Perry', year: 2008 },
    { name: 'Marry You', artist: 'Bruno Mars', year: 2010 },
    { name: 'When I Was Your Man', artist: 'Bruno Mars', year: 2012 },
    { name: '24K Magic', artist: 'Bruno Mars', year: 2016 },
    { name: 'Treasure', artist: 'Bruno Mars', year: 2012 },
    { name: 'Leave the Door Open', artist: 'Silk Sonic', year: 2021 },
    { name: 'Attention', artist: 'Charlie Puth', year: 2017 },
    { name: "We Don't Talk Anymore", artist: 'Charlie Puth', year: 2016 },
    { name: 'One Call Away', artist: 'Charlie Puth', year: 2015 },
    { name: "There's Nothing Holdin' Me Back", artist: 'Shawn Mendes', year: 2016 },
    { name: 'Treat You Better', artist: 'Shawn Mendes', year: 2016 },
    { name: 'Stitches', artist: 'Shawn Mendes', year: 2015 },
    { name: 'Mercy', artist: 'Shawn Mendes', year: 2016 },
    { name: 'Lost in Japan', artist: 'Shawn Mendes', year: 2018 },
    { name: 'Havana', artist: 'Camila Cabello', year: 2017 },
    { name: 'Never Be the Same', artist: 'Camila Cabello', year: 2017 },
    { name: "Don't Go Yet", artist: 'Camila Cabello', year: 2021 },
    { name: 'Bad Habits', artist: 'Ed Sheeran', year: 2021 },
    { name: 'Castle on the Hill', artist: 'Ed Sheeran', year: 2017 },
    { name: 'Galway Girl', artist: 'Ed Sheeran', year: 2017 },
    { name: 'Shivers', artist: 'Ed Sheeran', year: 2021 },
    { name: 'Eyes Closed', artist: 'Ed Sheeran', year: 2023 },
    { name: 'Too Sweet', artist: 'Hozier', year: 2024 },
    { name: 'Stay With Me', artist: 'Sam Smith', year: 2014 },
    { name: "I'm Not the Only One", artist: 'Sam Smith', year: 2014 },
    { name: 'Too Good at Goodbyes', artist: 'Sam Smith', year: 2017 },
    { name: 'Unholy', artist: 'Sam Smith', year: 2022 },
    { name: 'Dancing With a Stranger', artist: 'Sam Smith', year: 2019 },
    { name: 'Jealous', artist: 'Nick Jonas', year: 2014 },
    { name: 'Sucker', artist: 'Jonas Brothers', year: 2019 },
    { name: 'Cake by the Ocean', artist: 'DNCE', year: 2015 },
    { name: 'Believer', artist: 'Imagine Dragons', year: 2017 },
    { name: 'Thunder', artist: 'Imagine Dragons', year: 2017 },
    { name: 'Whatever It Takes', artist: 'Imagine Dragons', year: 2017 },
    { name: 'Enemy', artist: 'Imagine Dragons', year: 2021 },
    { name: 'Apologize', artist: 'OneRepublic', year: 2007 },
    { name: 'Secrets', artist: 'OneRepublic', year: 2009 },
    { name: 'Good Life', artist: 'OneRepublic', year: 2009 },
    { name: "I Ain't Worried", artist: 'OneRepublic', year: 2022 },
    { name: 'Viva La Vida', artist: 'Coldplay', year: 2008 },
    { name: 'Adventure of a Lifetime', artist: 'Coldplay', year: 2015 },
    { name: 'A Sky Full of Stars', artist: 'Coldplay', year: 2014 },
    { name: 'Paradise', artist: 'Coldplay', year: 2011 },
    { name: 'Fix You', artist: 'Coldplay', year: 2005 },
    { name: 'Girls Like You', artist: 'Maroon 5', year: 2017 },
    { name: 'Sugar', artist: 'Maroon 5', year: 2014 },
    { name: 'This Love', artist: 'Maroon 5', year: 2002 },
    { name: 'Maps', artist: 'Maroon 5', year: 2014 },
    { name: 'Memories', artist: 'Maroon 5', year: 2019 },
    { name: 'Makes Me Wonder', artist: 'Maroon 5', year: 2007 },
    { name: 'Diamonds', artist: 'Rihanna', year: 2012 },
    { name: 'We Found Love', artist: 'Rihanna', year: 2011 },
    { name: 'Only Girl', artist: 'Rihanna', year: 2010 },
    { name: 'Work', artist: 'Rihanna', year: 2016 },
  ],

  '2000s Hits': [
    { name: 'Hey Ya!', artist: 'OutKast', year: 2003 },
    { name: 'Ms. Jackson', artist: 'OutKast', year: 2000 },
    { name: 'The Way You Move', artist: 'OutKast', year: 2003 },
    { name: 'Lose Yourself', artist: 'Eminem', year: 2002 },
    { name: 'Without Me', artist: 'Eminem', year: 2002 },
    { name: 'Stan', artist: 'Eminem', year: 2000 },
    { name: 'Mockingbird', artist: 'Eminem', year: 2004 },
    { name: 'Gold Digger', artist: 'Kanye West', year: 2005 },
    { name: 'Stronger', artist: 'Kanye West', year: 2007 },
    { name: 'Heartless', artist: 'Kanye West', year: 2008 },
    { name: 'American Boy', artist: 'Estelle', year: 2008 },
    { name: 'Low', artist: 'Flo Rida', year: 2007 },
    { name: 'Sugar', artist: 'Flo Rida', year: 2009 },
    { name: 'Party in the U.S.A.', artist: 'Miley Cyrus', year: 2009 },
    { name: 'LoveGame', artist: 'Lady Gaga', year: 2008 },
    { name: 'Beautiful, Dirty, Rich', artist: 'Lady Gaga', year: 2008 },
    { name: 'Eh, Eh', artist: 'Lady Gaga', year: 2008 },
    { name: 'Underneath Your Clothes', artist: 'Shakira', year: 2001 },
    { name: 'Hollaback Girl', artist: 'Gwen Stefani', year: 2004 },
    { name: 'The Sweet Escape', artist: 'Gwen Stefani', year: 2006 },
    { name: 'Rich Girl', artist: 'Gwen Stefani', year: 2004 },
    { name: 'Gimme More', artist: 'Britney Spears', year: 2007 },
    { name: 'Piece of Me', artist: 'Britney Spears', year: 2007 },
    { name: "I'm a Slave 4 U", artist: 'Britney Spears', year: 2001 },
    { name: 'Circus', artist: 'Britney Spears', year: 2008 },
    { name: 'Dirrty', artist: 'Christina Aguilera', year: 2002 },
    { name: "Ain't No Other Man", artist: 'Christina Aguilera', year: 2006 },
    { name: 'Lady Marmalade', artist: 'Christina Aguilera', year: 2001 },
    { name: 'Family Affair', artist: 'Mary J. Blige', year: 2001 },
    { name: 'Be Without You', artist: 'Mary J. Blige', year: 2005 },
    { name: '1, 2 Step', artist: 'Ciara', year: 2004 },
    { name: 'Goodies', artist: 'Ciara', year: 2004 },
    { name: 'Like a Boy', artist: 'Ciara', year: 2006 },
    { name: 'My Love', artist: 'Justin Timberlake', year: 2006 },
    { name: 'LoveStoned', artist: 'Justin Timberlake', year: 2006 },
    { name: 'Summer Love', artist: 'Justin Timberlake', year: 2006 },
    { name: 'Senorita', artist: 'Justin Timberlake', year: 2002 },
    { name: 'Ignition (Remix)', artist: 'R. Kelly', year: 2002 },
    { name: 'Let Me Love You', artist: 'Mario', year: 2004 },
    { name: 'So Sick', artist: 'Ne-Yo', year: 2005 },
    { name: 'Because of You', artist: 'Ne-Yo', year: 2007 },
    { name: 'Closer', artist: 'Ne-Yo', year: 2008 },
    { name: 'Miss Independent', artist: 'Ne-Yo', year: 2008 },
    { name: 'Beautiful Girls', artist: 'Sean Kingston', year: 2007 },
    { name: 'Fire Burning', artist: 'Sean Kingston', year: 2009 },
    { name: 'Temperature', artist: 'Sean Paul', year: 2005 },
    { name: 'Get Busy', artist: 'Sean Paul', year: 2002 },
    { name: 'Gimme the Light', artist: 'Sean Paul', year: 2002 },
    { name: "It Wasn't Me", artist: 'Shaggy', year: 2000 },
    { name: 'Angel', artist: 'Shaggy', year: 2000 },
    { name: "Drop It Like It's Hot", artist: 'Snoop Dogg', year: 2004 },
    { name: 'Beautiful', artist: 'Snoop Dogg', year: 2002 },
    { name: 'Candy Shop', artist: '50 Cent', year: 2005 },
    { name: 'P.I.M.P.', artist: '50 Cent', year: 2003 },
    { name: 'Just a Lil Bit', artist: '50 Cent', year: 2005 },
    { name: 'Lean Back', artist: 'Terror Squad', year: 2004 },
    { name: 'Lollipop', artist: 'Lil Wayne', year: 2008 },
    { name: 'A Milli', artist: 'Lil Wayne', year: 2008 },
    { name: 'Live Your Life', artist: 'T.I.', year: 2008 },
    { name: 'Whatever You Like', artist: 'T.I.', year: 2008 },
    { name: 'Bring Em Out', artist: 'T.I.', year: 2004 },
    { name: 'Paper Planes', artist: 'M.I.A.', year: 2007 },
    { name: 'The Middle', artist: 'Jimmy Eat World', year: 2001 },
    { name: 'Mr. Brightside', artist: 'The Killers', year: 2003 },
    { name: 'Somebody Told Me', artist: 'The Killers', year: 2004 },
    { name: 'When You Were Young', artist: 'The Killers', year: 2006 },
    { name: 'Seven Nation Army', artist: 'The White Stripes', year: 2003 },
    { name: 'Feel Good Inc.', artist: 'Gorillaz', year: 2005 },
    { name: 'DARE', artist: 'Gorillaz', year: 2005 },
    { name: 'Last Nite', artist: 'The Strokes', year: 2001 },
    { name: 'Reptilia', artist: 'The Strokes', year: 2003 },
    { name: 'Take Me Out', artist: 'Franz Ferdinand', year: 2004 },
    { name: 'Float On', artist: 'Modest Mouse', year: 2004 },
    { name: 'Use Somebody', artist: 'Kings of Leon', year: 2008 },
    { name: 'Sex on Fire', artist: 'Kings of Leon', year: 2008 },
    { name: 'Boulevard of Broken Dreams', artist: 'Green Day', year: 2004 },
    { name: 'American Idiot', artist: 'Green Day', year: 2004 },
    { name: 'Wake Me Up When September Ends', artist: 'Green Day', year: 2004 },
    { name: 'Bring Me to Life', artist: 'Evanescence', year: 2003 },
    { name: 'My Immortal', artist: 'Evanescence', year: 2003 },
    { name: 'How You Remind Me', artist: 'Nickelback', year: 2001 },
    { name: 'Photograph', artist: 'Nickelback', year: 2005 },
    { name: 'Rockstar', artist: 'Nickelback', year: 2005 },
    { name: 'Drops of Jupiter', artist: 'Train', year: 2001 },
    { name: 'Hey, Soul Sister', artist: 'Train', year: 2009 },
    { name: 'Chasing Cars', artist: 'Snow Patrol', year: 2006 },
    { name: "You're Beautiful", artist: 'James Blunt', year: 2004 },
    { name: 'Bad Day', artist: 'Daniel Powter', year: 2005 },
    { name: 'A Thousand Miles', artist: 'Vanessa Carlton', year: 2002 },
    { name: 'Unwritten', artist: 'Natasha Bedingfield', year: 2004 },
    { name: 'These Words', artist: 'Natasha Bedingfield', year: 2004 },
    { name: 'Put Your Records On', artist: 'Corinne Bailey Rae', year: 2006 },
    { name: 'Bubbly', artist: 'Colbie Caillat', year: 2007 },
    { name: "I'm Yours", artist: 'Jason Mraz', year: 2008 },
    { name: 'Lucky', artist: 'Jason Mraz', year: 2008 },
    { name: 'Chasing Pavements', artist: 'Adele', year: 2008 },
    { name: 'Mercy', artist: 'Duffy', year: 2008 },
    { name: 'Grace Kelly', artist: 'Mika', year: 2007 },
    { name: 'Big Girl (You Are Beautiful)', artist: 'Mika', year: 2007 },
  ],
} satisfies Record<string, GenreSong[]>;
