type GenreSong = {
  name: string;
  artist: string;
  year: number;
};

export const EXTRA_GENRE_SONGS_CLASSICS = {
  'R&B': [
    { name: 'Sexual Healing', artist: 'Marvin Gaye', year: 1982 },
    { name: 'Let\'s Get It On', artist: 'Marvin Gaye', year: 1973 },
    { name: 'What\'s Going On', artist: 'Marvin Gaye', year: 1971 },
    { name: 'Ain\'t No Mountain High Enough', artist: 'Marvin Gaye & Tammi Terrell', year: 1967 },
    { name: 'Let\'s Stay Together', artist: 'Al Green', year: 1971 },
    { name: 'Tired of Being Alone', artist: 'Al Green', year: 1971 },
    { name: 'Love and Happiness', artist: 'Al Green', year: 1972 },
    { name: 'Superstition', artist: 'Stevie Wonder', year: 1972 },
    { name: 'Signed, Sealed, Delivered', artist: 'Stevie Wonder', year: 1970 },
    { name: 'Isn\'t She Lovely', artist: 'Stevie Wonder', year: 1976 },
    { name: 'I Just Called to Say I Love You', artist: 'Stevie Wonder', year: 1984 },
    { name: 'Respect', artist: 'Aretha Franklin', year: 1967 },
    { name: 'I Say a Little Prayer', artist: 'Aretha Franklin', year: 1968 },
    { name: 'Chain of Fools', artist: 'Aretha Franklin', year: 1967 },
    { name: 'Outstanding', artist: 'The Gap Band', year: 1982 },
    { name: 'You Dropped a Bomb on Me', artist: 'The Gap Band', year: 1982 },
    { name: 'Before I Let Go', artist: 'Maze & Frankie Beverly', year: 1981 },
    { name: 'Candy', artist: 'Cameo', year: 1986 },
    { name: 'Computer Love', artist: 'Zapp', year: 1985 },
    { name: 'Juicy Fruit', artist: 'Mtume', year: 1983 },
    { name: 'Sweet Love', artist: 'Anita Baker', year: 1986 },
    { name: 'Caught Up in the Rapture', artist: 'Anita Baker', year: 1986 },
    { name: 'Back at One', artist: 'Brian McKnight', year: 1999 },
    { name: 'Anytime', artist: 'Brian McKnight', year: 1997 },
    { name: 'End of the Road', artist: 'Boyz II Men', year: 1992 },
    { name: 'I\'ll Make Love to You', artist: 'Boyz II Men', year: 1994 },
    { name: 'On Bended Knee', artist: 'Boyz II Men', year: 1994 },
    { name: 'Can We Talk', artist: 'Tevin Campbell', year: 1993 },
    { name: 'Weak', artist: 'SWV', year: 1992 },
    { name: 'Right Here', artist: 'SWV', year: 1992 },
    { name: 'If You Love Me', artist: 'Brownstone', year: 1994 },
    { name: 'Don\'t Walk Away', artist: 'Jade', year: 1992 },
    { name: 'Just Kickin\' It', artist: 'Xscape', year: 1993 },
    { name: 'Understanding', artist: 'Xscape', year: 1993 },
    { name: 'Not Gon\' Cry', artist: 'Mary J. Blige', year: 1996 },
    { name: 'Family Affair', artist: 'Mary J. Blige', year: 2001 },
    { name: 'Doo Wop (That Thing)', artist: 'Lauryn Hill', year: 1998 },
    { name: 'Ex-Factor', artist: 'Lauryn Hill', year: 1998 },
    { name: 'Killing Me Softly', artist: 'Fugees', year: 1996 },
    { name: 'No Diggity', artist: 'Blackstreet', year: 1996 },
    { name: 'Pony', artist: 'Ginuwine', year: 1996 },
    { name: 'Twisted', artist: 'Keith Sweat', year: 1996 },
    { name: 'Freak Me', artist: 'Silk', year: 1992 },
    { name: 'Knockin\' Da Boots', artist: 'H-Town', year: 1993 },
    { name: 'Forever My Lady', artist: 'Jodeci', year: 1991 },
    { name: 'Come and Talk to Me', artist: 'Jodeci', year: 1991 },
    { name: 'Brown Sugar', artist: 'D\'Angelo', year: 1995 },
    { name: 'Untitled (How Does It Feel)', artist: 'D\'Angelo', year: 2000 },
    { name: 'Adorn', artist: 'Miguel', year: 2012 },
    { name: 'Sure Thing', artist: 'Miguel', year: 2010 },
    { name: 'Boo\'d Up', artist: 'Ella Mai', year: 2017 },
    { name: 'Trip', artist: 'Ella Mai', year: 2018 },
    { name: 'Focus', artist: 'H.E.R.', year: 2016 },
    { name: 'Best Part', artist: 'Daniel Caesar & H.E.R.', year: 2017 },
    { name: 'Leave the Door Open', artist: 'Silk Sonic', year: 2021 },
    { name: 'Smokin Out the Window', artist: 'Silk Sonic', year: 2021 },
    { name: 'Redbone', artist: 'Childish Gambino', year: 2016 },
    { name: 'Heartbreak Anniversary', artist: 'Giveon', year: 2020 },
    { name: 'Girls Need Love', artist: 'Summer Walker', year: 2018 },
    { name: 'Un-thinkable', artist: 'Alicia Keys', year: 2009 },
    { name: 'You Don\'t Know My Name', artist: 'Alicia Keys', year: 2003 },
    { name: 'Confessions Part II', artist: 'Usher', year: 2004 },
    { name: 'U Got It Bad', artist: 'Usher', year: 2001 },
    { name: 'Love T.K.O.', artist: 'Teddy Pendergrass', year: 1980 },
    { name: 'When Doves Cry', artist: 'Prince', year: 1984 },
    { name: 'Kiss', artist: 'Prince', year: 1986 },
    { name: 'The Most Beautiful Girl in the World', artist: 'Prince', year: 1994 },
    { name: 'Smooth Operator', artist: 'Sade', year: 1984 },
    { name: 'No Ordinary Love', artist: 'Sade', year: 1992 },
    { name: 'By Your Side', artist: 'Sade', year: 2000 },
    { name: 'Rock with You', artist: 'Michael Jackson', year: 1979 },
    { name: 'Remember the Time', artist: 'Michael Jackson', year: 1991 },
    { name: 'Human Nature', artist: 'Michael Jackson', year: 1982 },
    { name: 'I Wanna Be Down', artist: 'Brandy', year: 1994 },
    { name: 'Have You Ever', artist: 'Brandy', year: 1998 },
    { name: 'The Boy Is Mine', artist: 'Brandy & Monica', year: 1998 },
    { name: 'Before You Walk Out of My Life', artist: 'Monica', year: 1995 },
    { name: 'Angel of Mine', artist: 'Monica', year: 1998 },
    { name: 'Say My Name', artist: 'Destiny\'s Child', year: 1999 },
    { name: 'Bills, Bills, Bills', artist: 'Destiny\'s Child', year: 1999 },
    { name: 'Survivor', artist: 'Destiny\'s Child', year: 2001 },
    { name: 'Return of the Mack', artist: 'Mark Morrison', year: 1996 },
    { name: 'Rhythm of the Night', artist: 'DeBarge', year: 1985 },
    { name: 'I Like It', artist: 'DeBarge', year: 1982 },
    { name: 'Rock the Boat', artist: 'Aaliyah', year: 2001 },
    { name: 'Try Again', artist: 'Aaliyah', year: 2000 },
    { name: 'Are You That Somebody?', artist: 'Aaliyah', year: 1998 },
    { name: 'Foolish', artist: 'Ashanti', year: 2002 },
    { name: 'Rock Wit U', artist: 'Ashanti', year: 2003 },
    { name: 'All My Life', artist: 'K-Ci & JoJo', year: 1997 },
    { name: 'Tell Me It\'s Real', artist: 'K-Ci & JoJo', year: 1999 },
    { name: 'Peaches & Cream', artist: '112', year: 2001 },
    { name: 'Cupid', artist: '112', year: 1996 },
    { name: 'One in a Million', artist: 'Aaliyah', year: 1996 },
    { name: 'Differences', artist: 'Ginuwine', year: 2001 },
    { name: 'Freek\'n You', artist: 'Jodeci', year: 1995 },
    { name: 'Nobody', artist: 'Keith Sweat', year: 1996 },
    { name: 'Sweet Lady', artist: 'Tyrese', year: 1998 },
    { name: 'How You Gonna Act Like That', artist: 'Tyrese', year: 2002 },
    { name: 'Pretty Wings', artist: 'Maxwell', year: 2009 },
    { name: 'Ascension', artist: 'Maxwell', year: 1996 },
    { name: 'So Into You', artist: 'Tamia', year: 1998 },
    { name: 'Stranger in My House', artist: 'Tamia', year: 2000 },
  ],

  'Classic Hits': [
    { name: 'Africa', artist: 'Toto', year: 1982 },
    { name: 'Rosanna', artist: 'Toto', year: 1982 },
    { name: 'Sweet Dreams (Are Made of This)', artist: 'Eurythmics', year: 1983 },
    { name: 'Here Comes the Rain Again', artist: 'Eurythmics', year: 1983 },
    { name: 'Tainted Love', artist: 'Soft Cell', year: 1981 },
    { name: 'Come On Eileen', artist: 'Dexys Midnight Runners', year: 1982 },
    { name: '99 Luftballons', artist: 'Nena', year: 1983 },
    { name: 'The Safety Dance', artist: 'Men Without Hats', year: 1982 },
    { name: 'Video Killed the Radio Star', artist: 'The Buggles', year: 1979 },
    { name: 'I Ran', artist: 'A Flock of Seagulls', year: 1982 },
    { name: 'Maneater', artist: 'Hall & Oates', year: 1982 },
    { name: 'You Make My Dreams', artist: 'Hall & Oates', year: 1980 },
    { name: 'Jump', artist: 'Van Halen', year: 1984 },
    { name: 'Panama', artist: 'Van Halen', year: 1984 },
    { name: 'Here I Go Again', artist: 'Whitesnake', year: 1982 },
    { name: 'Eye of the Tiger', artist: 'Survivor', year: 1982 },
    { name: 'The Final Countdown', artist: 'Europe', year: 1986 },
    { name: 'Pour Some Sugar on Me', artist: 'Def Leppard', year: 1987 },
    { name: 'Love Bites', artist: 'Def Leppard', year: 1987 },
    { name: 'Another One Bites the Dust', artist: 'Queen', year: 1980 },
    { name: 'I Want to Break Free', artist: 'Queen', year: 1984 },
    { name: 'Under Pressure', artist: 'Queen & David Bowie', year: 1981 },
    { name: 'Another Brick in the Wall', artist: 'Pink Floyd', year: 1979 },
    { name: 'Start Me Up', artist: 'The Rolling Stones', year: 1981 },
    { name: 'Money for Nothing', artist: 'Dire Straits', year: 1985 },
    { name: 'Sledgehammer', artist: 'Peter Gabriel', year: 1986 },
    { name: 'Addicted to Love', artist: 'Robert Palmer', year: 1985 },
    { name: 'Dancing in the Dark', artist: 'Bruce Springsteen', year: 1984 },
    { name: 'Born in the U.S.A.', artist: 'Bruce Springsteen', year: 1984 },
    { name: 'The Way It Is', artist: 'Bruce Hornsby', year: 1986 },
    { name: 'Higher Love', artist: 'Steve Winwood', year: 1986 },
    { name: 'Don\'t Dream It\'s Over', artist: 'Crowded House', year: 1986 },
    { name: 'Down Under', artist: 'Men at Work', year: 1981 },
    { name: 'We Built This City', artist: 'Starship', year: 1985 },
    { name: 'Nothing\'s Gonna Stop Us Now', artist: 'Starship', year: 1987 },
    { name: 'Separate Ways', artist: 'Journey', year: 1983 },
    { name: 'Open Arms', artist: 'Journey', year: 1981 },
    { name: 'Kyrie', artist: 'Mr. Mister', year: 1985 },
    { name: 'Owner of a Lonely Heart', artist: 'Yes', year: 1983 },
    { name: 'Heat of the Moment', artist: 'Asia', year: 1982 },
    { name: 'Voices Carry', artist: 'Til Tuesday', year: 1985 },
    { name: 'Everybody Wants to Rule the World', artist: 'Tears for Fears', year: 1985 },
    { name: 'Head Over Heels', artist: 'Tears for Fears', year: 1985 },
    { name: 'True', artist: 'Spandau Ballet', year: 1983 },
    { name: 'West End Girls', artist: 'Pet Shop Boys', year: 1984 },
    { name: 'You Spin Me Round', artist: 'Dead or Alive', year: 1984 },
    { name: 'Never Gonna Give You Up', artist: 'Rick Astley', year: 1987 },
    { name: 'Together Forever', artist: 'Rick Astley', year: 1987 },
    { name: 'She Drives Me Crazy', artist: 'Fine Young Cannibals', year: 1988 },
    { name: 'Red Red Wine', artist: 'UB40', year: 1983 },
    { name: 'Electric Avenue', artist: 'Eddy Grant', year: 1982 },
    { name: 'Caribbean Queen', artist: 'Billy Ocean', year: 1984 },
    { name: 'Get Outta My Dreams, Get Into My Car', artist: 'Billy Ocean', year: 1988 },
    { name: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper', year: 1983 },
    { name: 'Time After Time', artist: 'Cyndi Lauper', year: 1983 },
    { name: 'True Colors', artist: 'Cyndi Lauper', year: 1986 },
    { name: 'Like a Virgin', artist: 'Madonna', year: 1984 },
    { name: 'Into the Groove', artist: 'Madonna', year: 1985 },
    { name: 'Holiday', artist: 'Madonna', year: 1983 },
    { name: 'Smooth Criminal', artist: 'Michael Jackson', year: 1987 },
    { name: 'Bad', artist: 'Michael Jackson', year: 1987 },
    { name: 'The Way You Make Me Feel', artist: 'Michael Jackson', year: 1987 },
    { name: 'Part-Time Lover', artist: 'Stevie Wonder', year: 1985 },
    { name: 'All Night Long', artist: 'Lionel Richie', year: 1983 },
    { name: 'Hello', artist: 'Lionel Richie', year: 1984 },
    { name: 'Dancing on the Ceiling', artist: 'Lionel Richie', year: 1986 },
    { name: 'Let\'s Groove', artist: 'Earth Wind & Fire', year: 1981 },
    { name: 'Super Freak', artist: 'Rick James', year: 1981 },
    { name: 'Word Up!', artist: 'Cameo', year: 1986 },
    { name: 'Nasty', artist: 'Janet Jackson', year: 1986 },
    { name: 'Miss You Much', artist: 'Janet Jackson', year: 1989 },
    { name: 'Straight Up', artist: 'Paula Abdul', year: 1988 },
    { name: 'Opposites Attract', artist: 'Paula Abdul', year: 1989 },
    { name: 'Every Breath You Take', artist: 'The Police', year: 1983 },
    { name: 'Roxanne', artist: 'The Police', year: 1978 },
    { name: 'Message in a Bottle', artist: 'The Police', year: 1979 },
    { name: 'Don\'t You Want Me', artist: 'The Human League', year: 1981 },
    { name: 'Take On Me', artist: 'a-ha', year: 1985 },
    { name: 'Wake Me Up Before You Go-Go', artist: 'Wham!', year: 1984 },
    { name: 'Careless Whisper', artist: 'George Michael', year: 1984 },
    { name: 'Faith', artist: 'George Michael', year: 1987 },
    { name: 'Against All Odds', artist: 'Phil Collins', year: 1984 },
    { name: 'In the Air Tonight', artist: 'Phil Collins', year: 1981 },
    { name: 'Another Day in Paradise', artist: 'Phil Collins', year: 1989 },
    { name: 'Karma Chameleon', artist: 'Culture Club', year: 1983 },
    { name: 'Do You Really Want to Hurt Me', artist: 'Culture Club', year: 1982 },
    { name: 'Hungry Like the Wolf', artist: 'Duran Duran', year: 1982 },
    { name: 'Rio', artist: 'Duran Duran', year: 1982 },
    { name: 'The Reflex', artist: 'Duran Duran', year: 1984 },
    { name: 'Take My Breath Away', artist: 'Berlin', year: 1986 },
    { name: 'Maniac', artist: 'Michael Sembello', year: 1983 },
    { name: 'Footloose', artist: 'Kenny Loggins', year: 1984 },
    { name: 'Danger Zone', artist: 'Kenny Loggins', year: 1986 },
    { name: 'The Power of Love', artist: 'Huey Lewis & The News', year: 1985 },
    { name: 'St. Elmo\'s Fire', artist: 'John Parr', year: 1985 },
    { name: 'Glory of Love', artist: 'Peter Cetera', year: 1986 },
    { name: 'I Think We\'re Alone Now', artist: 'Tiffany', year: 1987 },
    { name: 'Only in My Dreams', artist: 'Debbie Gibson', year: 1986 },
    { name: 'Self Control', artist: 'Laura Branigan', year: 1984 },
    { name: 'Gloria', artist: 'Laura Branigan', year: 1982 },
    { name: 'Broken Wings', artist: 'Mr. Mister', year: 1985 },
    { name: 'I Want to Know What Love Is', artist: 'Foreigner', year: 1984 },
    { name: 'Waiting for a Girl Like You', artist: 'Foreigner', year: 1981 },
    { name: 'Centerfold', artist: 'The J. Geils Band', year: 1981 },
    { name: 'Jack & Diane', artist: 'John Mellencamp', year: 1982 },
    { name: 'Hurts So Good', artist: 'John Mellencamp', year: 1982 },
    { name: 'Small Town', artist: 'John Mellencamp', year: 1985 },
    { name: 'The Boys of Summer', artist: 'Don Henley', year: 1984 },
    { name: 'The Heat Is On', artist: 'Glenn Frey', year: 1984 },
    { name: 'Your Love', artist: 'The Outfield', year: 1985 },
    { name: 'Every Rose Has Its Thorn', artist: 'Poison', year: 1988 },
    { name: 'Heaven', artist: 'Warrant', year: 1989 },
    { name: 'Alone', artist: 'Heart', year: 1987 },
    { name: 'These Dreams', artist: 'Heart', year: 1985 },
    { name: 'We Belong', artist: 'Pat Benatar', year: 1984 },
    { name: 'Love Is a Battlefield', artist: 'Pat Benatar', year: 1983 },
    { name: 'Sunglasses at Night', artist: 'Corey Hart', year: 1984 },
    { name: 'Bette Davis Eyes', artist: 'Kim Carnes', year: 1981 },
    { name: 'Mickey', artist: 'Toni Basil', year: 1981 },
    { name: 'I Melt with You', artist: 'Modern English', year: 1982 },
    { name: 'Major Tom', artist: 'Peter Schilling', year: 1983 },
    { name: 'Vienna', artist: 'Ultravox', year: 1980 },
    { name: 'Too Shy', artist: 'Kajagoogoo', year: 1983 },
  ],

  '90s Hits': [
    { name: 'Vogue', artist: 'Madonna', year: 1990 },
    { name: 'Ray of Light', artist: 'Madonna', year: 1998 },
    { name: 'Black or White', artist: 'Michael Jackson', year: 1991 },
    { name: 'Remember the Time', artist: 'Michael Jackson', year: 1991 },
    { name: 'You Are Not Alone', artist: 'Michael Jackson', year: 1995 },
    { name: 'Genie in a Bottle', artist: 'Christina Aguilera', year: 1999 },
    { name: 'What a Girl Wants', artist: 'Christina Aguilera', year: 1999 },
    { name: 'Livin\' la Vida Loca', artist: 'Ricky Martin', year: 1999 },
    { name: 'She Bangs', artist: 'Ricky Martin', year: 2000 },
    { name: 'Mambo No. 5', artist: 'Lou Bega', year: 1999 },
    { name: 'Blue (Da Ba Dee)', artist: 'Eiffel 65', year: 1998 },
    { name: 'Believe', artist: 'Cher', year: 1998 },
    { name: 'The Sign', artist: 'Ace of Base', year: 1993 },
    { name: 'All That She Wants', artist: 'Ace of Base', year: 1992 },
    { name: 'Torn', artist: 'Natalie Imbruglia', year: 1997 },
    { name: 'Un-Break My Heart', artist: 'Toni Braxton', year: 1996 },
    { name: 'This Is How We Do It', artist: 'Montell Jordan', year: 1995 },
    { name: 'Regulate', artist: 'Warren G', year: 1994 },
    { name: 'Gangsta\'s Paradise', artist: 'Coolio', year: 1995 },
    { name: 'California Love', artist: '2Pac', year: 1995 },
    { name: 'Changes', artist: '2Pac', year: 1998 },
    { name: 'Hypnotize', artist: 'The Notorious B.I.G.', year: 1997 },
    { name: 'Mo Money Mo Problems', artist: 'The Notorious B.I.G.', year: 1997 },
    { name: 'Juicy', artist: 'The Notorious B.I.G.', year: 1994 },
    { name: 'Jump Around', artist: 'House of Pain', year: 1992 },
    { name: 'Insane in the Brain', artist: 'Cypress Hill', year: 1993 },
    { name: 'Intergalactic', artist: 'Beastie Boys', year: 1998 },
    { name: 'Sabotage', artist: 'Beastie Boys', year: 1994 },
    { name: 'C.R.E.A.M.', artist: 'Wu-Tang Clan', year: 1993 },
    { name: 'Can I Kick It?', artist: 'A Tribe Called Quest', year: 1990 },
    { name: 'O.P.P.', artist: 'Naughty by Nature', year: 1991 },
    { name: 'Hip Hop Hooray', artist: 'Naughty by Nature', year: 1992 },
    { name: 'Shoop', artist: 'Salt-N-Pepa', year: 1993 },
    { name: 'Whatta Man', artist: 'Salt-N-Pepa', year: 1993 },
    { name: 'Baby Got Back', artist: 'Sir Mix-A-Lot', year: 1992 },
    { name: 'Whoomp! (There It Is)', artist: 'Tag Team', year: 1993 },
    { name: 'Gonna Make You Sweat', artist: 'C+C Music Factory', year: 1990 },
    { name: 'Rhythm Is a Dancer', artist: 'Snap!', year: 1992 },
    { name: 'What Is Love', artist: 'Haddaway', year: 1993 },
    { name: 'Be My Lover', artist: 'La Bouche', year: 1995 },
    { name: 'Another Night', artist: 'Real McCoy', year: 1993 },
    { name: 'The Rhythm of the Night', artist: 'Corona', year: 1993 },
    { name: 'Show Me Love', artist: 'Robin S.', year: 1990 },
    { name: 'Finally', artist: 'CeCe Peniston', year: 1991 },
    { name: 'Groove Is in the Heart', artist: 'Deee-Lite', year: 1990 },
    { name: 'Around the World', artist: 'Daft Punk', year: 1997 },
    { name: 'Praise You', artist: 'Fatboy Slim', year: 1998 },
    { name: 'Firestarter', artist: 'The Prodigy', year: 1996 },
    { name: 'Song 2', artist: 'Blur', year: 1997 },
    { name: 'Bitter Sweet Symphony', artist: 'The Verve', year: 1997 },
    { name: 'Tubthumping', artist: 'Chumbawamba', year: 1997 },
    { name: 'Semi-Charmed Life', artist: 'Third Eye Blind', year: 1997 },
    { name: 'Jumper', artist: 'Third Eye Blind', year: 1997 },
    { name: 'Two Princes', artist: 'Spin Doctors', year: 1991 },
    { name: 'One Week', artist: 'Barenaked Ladies', year: 1998 },
    { name: 'You Get What You Give', artist: 'New Radicals', year: 1998 },
    { name: 'Breakfast at Tiffany\'s', artist: 'Deep Blue Something', year: 1995 },
    { name: 'Closing Time', artist: 'Semisonic', year: 1998 },
    { name: 'Inside Out', artist: 'Eve 6', year: 1998 },
    { name: 'All Star', artist: 'Smash Mouth', year: 1999 },
    { name: 'Walkin\' on the Sun', artist: 'Smash Mouth', year: 1997 },
    { name: 'Santeria', artist: 'Sublime', year: 1996 },
    { name: 'What I Got', artist: 'Sublime', year: 1996 },
    { name: 'Fly', artist: 'Sugar Ray', year: 1997 },
    { name: 'Every Morning', artist: 'Sugar Ray', year: 1998 },
    { name: 'Iris', artist: 'Goo Goo Dolls', year: 1998 },
    { name: 'Slide', artist: 'Goo Goo Dolls', year: 1998 },
    { name: '3AM', artist: 'Matchbox Twenty', year: 1996 },
    { name: 'Push', artist: 'Matchbox Twenty', year: 1996 },
    { name: 'Mr. Jones', artist: 'Counting Crows', year: 1993 },
    { name: 'Run-Around', artist: 'Blues Traveler', year: 1994 },
    { name: 'One', artist: 'U2', year: 1991 },
    { name: 'Under the Bridge', artist: 'Red Hot Chili Peppers', year: 1991 },
    { name: 'Loser', artist: 'Beck', year: 1993 },
    { name: 'No Rain', artist: 'Blind Melon', year: 1992 },
    { name: 'Cannonball', artist: 'The Breeders', year: 1993 },
    { name: 'Buddy Holly', artist: 'Weezer', year: 1994 },
    { name: 'Say It Ain\'t So', artist: 'Weezer', year: 1994 },
    { name: '1979', artist: 'The Smashing Pumpkins', year: 1995 },
    { name: 'Bullet with Butterfly Wings', artist: 'The Smashing Pumpkins', year: 1995 },
    { name: 'Everlong', artist: 'Foo Fighters', year: 1997 },
    { name: 'Learn to Fly', artist: 'Foo Fighters', year: 1999 },
    { name: 'All the Small Things', artist: 'Blink-182', year: 1999 },
    { name: 'What\'s My Age Again?', artist: 'Blink-182', year: 1999 },
    { name: 'My Own Worst Enemy', artist: 'Lit', year: 1999 },
    { name: 'The Impression That I Get', artist: 'The Mighty Mighty Bosstones', year: 1997 },
    { name: 'Flagpole Sitta', artist: 'Harvey Danger', year: 1997 },
    { name: 'Peaches', artist: 'The Presidents of the United States of America', year: 1995 },
    { name: 'Kiss Me', artist: 'Sixpence None the Richer', year: 1998 },
    { name: 'I Don\'t Want to Wait', artist: 'Paula Cole', year: 1996 },
    { name: 'Criminal', artist: 'Fiona Apple', year: 1996 },
    { name: 'You Were Meant for Me', artist: 'Jewel', year: 1995 },
    { name: 'Save Tonight', artist: 'Eagle-Eye Cherry', year: 1997 },
    { name: 'How Bizarre', artist: 'OMC', year: 1995 },
    { name: 'Cotton Eye Joe', artist: 'Rednex', year: 1994 },
    { name: 'Macarena', artist: 'Los Del Río', year: 1993 },
    { name: 'Virtual Insanity', artist: 'Jamiroquai', year: 1996 },
    { name: 'You Gotta Be', artist: 'Des\'ree', year: 1994 },
    { name: 'Stay', artist: 'Lisa Loeb', year: 1994 },
    { name: 'Missing', artist: 'Everything But The Girl', year: 1994 },
    { name: 'I Love You Always Forever', artist: 'Donna Lewis', year: 1996 },
    { name: 'I\'ll Be', artist: 'Edwin McCain', year: 1997 },
    { name: 'The Freshmen', artist: 'The Verve Pipe', year: 1996 },
  ],
} satisfies Record<string, GenreSong[]>;
