type GenreSong = {
  name: string;
  artist: string;
  year: number;
};

export const EXTRA_GENRE_SONGS_LATIN = {
  'EDM': [
    { name: 'Spaceman', artist: 'Hardwell', year: 2012 },
    { name: 'Apollo', artist: 'Hardwell', year: 2012 },
    { name: 'Runaway (U & I)', artist: 'Galantis', year: 2014 },
    { name: 'Peanut Butter Jelly', artist: 'Galantis', year: 2015 },
    { name: 'No Money', artist: 'Galantis', year: 2016 },
    { name: 'I Love It', artist: 'Icona Pop', year: 2012 },
    { name: 'I Could Be the One', artist: 'Avicii & Nicky Romero', year: 2012 },
    { name: 'Toulouse', artist: 'Nicky Romero', year: 2011 },
    { name: 'The Nights', artist: 'Avicii', year: 2014 },
    { name: 'Without You', artist: 'Avicii', year: 2017 },
    { name: 'Lonely Together', artist: 'Avicii', year: 2017 },
    { name: 'SOS', artist: 'Avicii', year: 2019 },
    { name: 'Tremor', artist: 'Dimitri Vegas & Like Mike', year: 2014 },
    { name: 'Mammoth', artist: 'Dimitri Vegas & Like Mike', year: 2013 },
    { name: 'The Hum', artist: 'Dimitri Vegas & Like Mike', year: 2015 },
    { name: 'Waves', artist: 'Mr. Probz', year: 2014 },
    { name: 'Booyah', artist: 'Showtek', year: 2013 },
    { name: 'Cheerleader', artist: 'OMI', year: 2014 },
    { name: 'Ocean', artist: 'Martin Garrix', year: 2018 },
    { name: 'Wizard', artist: 'Martin Garrix & Jay Hardway', year: 2013 },
    { name: 'Adagio for Strings', artist: 'Tiësto', year: 2005 },
    { name: 'Secrets', artist: 'Tiësto & KSHMR', year: 2015 },
    { name: 'Take Over Control', artist: 'Afrojack', year: 2010 },
    { name: 'Pursuit of Happiness', artist: 'Kid Cudi & Steve Aoki', year: 2012 },
    { name: 'A Light That Never Comes', artist: 'Steve Aoki & Linkin Park', year: 2013 },
    { name: 'Tsunami', artist: 'DVBBS & Borgeous', year: 2013 },
    { name: 'Five Hours', artist: 'Deorro', year: 2014 },
    { name: 'Five More Hours', artist: 'Deorro & Chris Brown', year: 2015 },
    { name: 'This Is What It Feels Like', artist: 'Armin van Buuren', year: 2013 },
    { name: 'Spectrum', artist: 'Zedd', year: 2012 },
    { name: 'Find You', artist: 'Zedd', year: 2014 },
    { name: 'If I Lose Myself', artist: 'Alesso vs OneRepublic', year: 2013 },
    { name: 'Heroes (We Could Be)', artist: 'Alesso', year: 2014 },
    { name: 'Under Control', artist: 'Calvin Harris & Alesso', year: 2013 },
    { name: 'Reload', artist: 'Sebastian Ingrosso & Tommy Trash', year: 2012 },
    { name: 'Sun Is Shining', artist: 'Axwell Λ Ingrosso', year: 2015 },
    { name: 'One (Your Name)', artist: 'Swedish House Mafia', year: 2010 },
    { name: 'Miami 2 Ibiza', artist: 'Swedish House Mafia', year: 2010 },
    { name: 'Turn Down for What', artist: 'DJ Snake & Lil Jon', year: 2013 },
    { name: 'Get Low', artist: 'Dillon Francis & DJ Snake', year: 2014 },
    { name: 'You Know You Like It', artist: 'DJ Snake & AlunaGeorge', year: 2014 },
    { name: 'Middle', artist: 'DJ Snake', year: 2015 },
    { name: 'Lovers on the Sun', artist: 'David Guetta', year: 2014 },
    { name: 'Shot Me Down', artist: 'David Guetta', year: 2014 },
    { name: 'Play Hard', artist: 'David Guetta', year: 2012 },
    { name: 'She Wolf (Falling to Pieces)', artist: 'David Guetta', year: 2012 },
    { name: 'Dangerous', artist: 'David Guetta', year: 2014 },
    { name: 'Hey Mama', artist: 'David Guetta', year: 2015 },
    { name: 'Sweet Nothing', artist: 'Calvin Harris', year: 2012 },
    { name: 'Outside', artist: 'Calvin Harris', year: 2014 },
    { name: 'Blame', artist: 'Calvin Harris', year: 2014 },
    { name: 'Call On Me', artist: 'Eric Prydz', year: 2004 },
    { name: 'Better Off Alone', artist: 'Alice Deejay', year: 1998 },
    { name: 'Scary Monsters and Nice Sprites', artist: 'Skrillex', year: 2010 },
    { name: 'Summertime Sadness (Cedric Gervais Remix)', artist: 'Lana Del Rey', year: 2013 },
    { name: 'Hideaway', artist: 'Kiesza', year: 2014 },
    { name: 'Sugar', artist: 'Robin Schulz', year: 2015 },
    { name: 'Are You With Me', artist: 'Lost Frequencies', year: 2014 },
    { name: 'Reality', artist: 'Lost Frequencies', year: 2015 },
    { name: 'Happier', artist: 'Marshmello & Bastille', year: 2018 },
    { name: 'Friends', artist: 'Marshmello & Anne-Marie', year: 2018 },
    { name: 'Wolves', artist: 'Selena Gomez & Marshmello', year: 2017 },
    { name: 'Symphony', artist: 'Clean Bandit', year: 2017 },
    { name: 'Solo', artist: 'Clean Bandit', year: 2018 },
  ],
  'Pop Latino': [
    { name: 'Color Esperanza', artist: 'Diego Torres', year: 2001 },
    { name: 'Tratar de Estar Mejor', artist: 'Diego Torres', year: 1994 },
    { name: 'Me Va a Extrañar', artist: 'Ricardo Montaner', year: 1988 },
    { name: 'Tan Enamorados', artist: 'Ricardo Montaner', year: 1989 },
    { name: 'Me Muero', artist: 'La Quinta Estación', year: 2006 },
    { name: 'Corazón Partío', artist: 'Alejandro Sanz', year: 1997 },
    { name: 'Amiga Mía', artist: 'Alejandro Sanz', year: 1997 },
    { name: 'Y Si Fuera Ella', artist: 'Alejandro Sanz', year: 1997 },
    { name: 'No Es lo Mismo', artist: 'Alejandro Sanz', year: 2003 },
    { name: 'Bulería', artist: 'David Bisbal', year: 2004 },
    { name: 'Darte un Beso', artist: 'Prince Royce', year: 2013 },
    { name: 'Stand by Me', artist: 'Prince Royce', year: 2010 },
    { name: 'Corazón Sin Cara', artist: 'Prince Royce', year: 2010 },
    { name: 'Las Cosas Pequeñas', artist: 'Prince Royce', year: 2012 },
    { name: 'Incondicional', artist: 'Prince Royce', year: 2012 },
    { name: 'El Amor Que Perdimos', artist: 'Prince Royce', year: 2010 },
    { name: 'Propuesta Indecente', artist: 'Romeo Santos', year: 2013 },
    { name: 'Eres Mía', artist: 'Romeo Santos', year: 2014 },
    { name: 'Odio', artist: 'Romeo Santos', year: 2014 },
    { name: 'Imitadora', artist: 'Romeo Santos', year: 2017 },
    { name: 'Sobredosis', artist: 'Romeo Santos', year: 2017 },
    { name: 'Bachata Rosa', artist: 'Juan Luis Guerra', year: 1990 },
    { name: 'Frío Frío', artist: 'Juan Luis Guerra', year: 1992 },
    { name: 'Visa Para un Sueño', artist: 'Juan Luis Guerra', year: 1989 },
    { name: 'El Niágara en Bicicleta', artist: 'Juan Luis Guerra', year: 1998 },
    { name: 'La Llave de Mi Corazón', artist: 'Juan Luis Guerra', year: 2007 },
    { name: 'Bachata en Fukuoka', artist: 'Juan Luis Guerra', year: 2010 },
    { name: 'La Gozadera', artist: 'Gente de Zona', year: 2015 },
    { name: 'Traidora', artist: 'Gente de Zona', year: 2015 },
    { name: 'El Sol No Regresa', artist: 'La Quinta Estación', year: 2004 },
    { name: 'La Playa', artist: 'La Oreja de Van Gogh', year: 2000 },
    { name: 'Bailando', artist: 'Gente de Zona', year: 2014 },
    { name: 'La Mordidita', artist: 'Ricky Martin', year: 2015 },
    { name: 'Vente Pa Ca', artist: 'Ricky Martin', year: 2016 },
    { name: 'Tal Vez', artist: 'Ricky Martin', year: 2003 },
    { name: 'Tu Recuerdo', artist: 'Ricky Martin', year: 2006 },
    { name: 'Vuelve', artist: 'Ricky Martin', year: 1998 },
    { name: 'Adrenalina', artist: 'Wisin', year: 2014 },
    { name: 'Escápate Conmigo', artist: 'Wisin', year: 2017 },
    { name: 'Que Viva la Vida', artist: 'Wisin', year: 2013 },
    { name: 'Duele el Corazón', artist: 'Enrique Iglesias', year: 2016 },
    { name: 'Súbeme la Radio', artist: 'Enrique Iglesias', year: 2017 },
    { name: 'Tonight', artist: 'Enrique Iglesias', year: 2010 },
    { name: 'I Like It', artist: 'Enrique Iglesias', year: 2010 },
    { name: 'Cuando Me Enamoro', artist: 'Enrique Iglesias', year: 2010 },
    { name: 'Me Pasé', artist: 'Enrique Iglesias', year: 2021 },
    { name: 'Rabiosa', artist: 'Shakira', year: 2010 },
    { name: 'Addicted to You', artist: 'Shakira', year: 2012 },
    { name: 'Me Enamoré', artist: 'Shakira', year: 2017 },
    { name: 'Chantaje', artist: 'Shakira', year: 2016 },
    { name: 'Las de la Intuición', artist: 'Shakira', year: 2005 },
    { name: 'Día de Enero', artist: 'Shakira', year: 2005 },
    { name: 'Suerte', artist: 'Shakira', year: 2001 },
    { name: 'Estoy Aquí', artist: 'Shakira', year: 1995 },
    { name: 'Antología', artist: 'Shakira', year: 1995 },
    { name: 'Ojos Así', artist: 'Shakira', year: 1998 },
    { name: 'Me Voy', artist: 'Julieta Venegas', year: 2006 },
    { name: 'Limón y Sal', artist: 'Julieta Venegas', year: 2006 },
    { name: 'Eres Para Mí', artist: 'Julieta Venegas', year: 2006 },
    { name: 'Andar Conmigo', artist: 'Julieta Venegas', year: 2003 },
    { name: 'Lento', artist: 'Julieta Venegas', year: 2003 },
    { name: 'Fotografía', artist: 'Juanes', year: 2002 },
    { name: 'Volverte a Ver', artist: 'Juanes', year: 2004 },
    { name: 'Nada Valgo Sin Tu Amor', artist: 'Juanes', year: 2004 },
    { name: 'Es Por Ti', artist: 'Juanes', year: 2002 },
    { name: 'Yerbatero', artist: 'Juanes', year: 2010 },
    { name: 'Azul', artist: 'Cristian Castro', year: 2001 },
    { name: 'Fruta Fresca', artist: 'Carlos Vives', year: 1999 },
    { name: 'Volví a Nacer', artist: 'Carlos Vives', year: 2012 },
    { name: 'Robarte un Beso', artist: 'Carlos Vives', year: 2017 },
    { name: 'Déjame Entrar', artist: 'Carlos Vives', year: 2001 },
    { name: 'Cuando Nos Volvamos a Encontrar', artist: 'Carlos Vives', year: 2014 },
    { name: 'Colgando en Tus Manos', artist: 'Carlos Baute', year: 2008 },
    { name: 'Rebelde', artist: 'RBD', year: 2004 },
    { name: 'Solo Quédate en Silencio', artist: 'RBD', year: 2004 },
    { name: 'Yo Quisiera', artist: 'Reik', year: 2005 },
    { name: 'Noviembre Sin Ti', artist: 'Reik', year: 2005 },
    { name: 'Me Niego', artist: 'Reik', year: 2018 },
    { name: 'Creo en Ti', artist: 'Reik', year: 2011 },
    { name: 'Sálvame', artist: 'RBD', year: 2004 },
    { name: 'Kilómetros', artist: 'Sin Bandera', year: 2002 },
    { name: 'Entra en Mi Vida', artist: 'Sin Bandera', year: 2002 },
    { name: 'Suelta Mi Mano', artist: 'Sin Bandera', year: 2005 },
    { name: 'Que Lloro', artist: 'Sin Bandera', year: 2003 },
    { name: 'Mientes Tan Bien', artist: 'Sin Bandera', year: 2003 },
    { name: 'Todo Cambió', artist: 'Camila', year: 2006 },
    { name: 'Mientes', artist: 'Camila', year: 2010 },
    { name: 'Aléjate de Mí', artist: 'Camila', year: 2010 },
    { name: 'Abrázame', artist: 'Camila', year: 2006 },
    { name: 'Coleccionista de Canciones', artist: 'Camila', year: 2006 },
    { name: 'Corre', artist: 'Jesse & Joy', year: 2011 },
    { name: 'Espacio Sideral', artist: 'Jesse & Joy', year: 2006 },
    { name: 'Dueles', artist: 'Jesse & Joy', year: 2015 },
    { name: 'La de la Mala Suerte', artist: 'Jesse & Joy', year: 2011 },
    { name: 'Ecos de Amor', artist: 'Jesse & Joy', year: 2015 },
    { name: 'Tú', artist: 'Noelia', year: 1999 },
    { name: 'Mi Mayor Anhelo', artist: 'Banda MS', year: 2012 },
    { name: 'Solo Con Verte', artist: 'Banda MS', year: 2015 },
    { name: 'Calma', artist: 'Pedro Capó', year: 2018 },
  ],
  'Reggaetón': [
    { name: 'Lo Que Pasó Pasó', artist: 'Daddy Yankee', year: 2004 },
    { name: 'Rompe', artist: 'Daddy Yankee', year: 2005 },
    { name: 'Ella Me Levantó', artist: 'Daddy Yankee', year: 2007 },
    { name: 'Pose', artist: 'Daddy Yankee', year: 2008 },
    { name: 'Llamado de Emergencia', artist: 'Daddy Yankee', year: 2008 },
    { name: 'La Despedida', artist: 'Daddy Yankee', year: 2010 },
    { name: 'Lovumba', artist: 'Daddy Yankee', year: 2011 },
    { name: 'Dura', artist: 'Daddy Yankee', year: 2018 },
    { name: 'Que Tire Pa Lante', artist: 'Daddy Yankee', year: 2019 },
    { name: 'Mayor Que Yo', artist: 'Baby Ranks', year: 2005 },
    { name: 'Noche de Sexo', artist: 'Wisin & Yandel', year: 2005 },
    { name: 'Pam Pam', artist: 'Wisin & Yandel', year: 2006 },
    { name: 'Sexy Movimiento', artist: 'Wisin & Yandel', year: 2007 },
    { name: 'Abusadora', artist: 'Wisin & Yandel', year: 2009 },
    { name: 'Me Estás Tentando', artist: 'Wisin & Yandel', year: 2008 },
    { name: 'Algo Me Gusta de Ti', artist: 'Wisin & Yandel', year: 2012 },
    { name: 'Noche de Entierro', artist: 'Los Benjamins', year: 2006 },
    { name: 'Mayor Que Yo 3', artist: 'Luny Tunes', year: 2015 },
    { name: 'Gata Only', artist: 'FloyyMenor & Cris MJ', year: 2024 },
    { name: 'Dile', artist: 'Don Omar', year: 2003 },
    { name: 'Pobre Diabla', artist: 'Don Omar', year: 2003 },
    { name: 'Dale Don Dale', artist: 'Don Omar', year: 2003 },
    { name: 'Salió el Sol', artist: 'Don Omar', year: 2006 },
    { name: 'Taboo', artist: 'Don Omar', year: 2011 },
    { name: 'Hasta Abajo', artist: 'Don Omar', year: 2009 },
    { name: 'Zumba', artist: 'Don Omar', year: 2012 },
    { name: 'Danza Kuduro', artist: 'Lucenzo', year: 2010 },
    { name: 'Ven Báilalo', artist: 'Angel y Khriz', year: 2004 },
    { name: 'Na De Na', artist: 'Angel y Khriz', year: 2008 },
    { name: 'Atrévete-Te-Te', artist: 'Calle 13', year: 2005 },
    { name: 'Con Altura', artist: 'Rosalía & J Balvin', year: 2019 },
    { name: 'Perdóname', artist: 'La Factoría', year: 2007 },
    { name: 'Si No Le Contesto', artist: 'Plan B', year: 2010 },
    { name: 'Fanática Sensual', artist: 'Plan B', year: 2014 },
    { name: 'Candy', artist: 'Plan B', year: 2014 },
    { name: 'Mi Vecinita', artist: 'Plan B', year: 2014 },
    { name: 'Te Dijeron', artist: 'Plan B', year: 2014 },
    { name: 'Me Niegas', artist: 'Baby Rasta & Gringo', year: 2013 },
    { name: 'Un Beso', artist: 'Aventura', year: 2005 },
    { name: 'Noche de Travesura', artist: 'Héctor El Father', year: 2005 },
    { name: 'Sola', artist: 'Héctor El Father', year: 2006 },
    { name: 'Todo de Ti', artist: 'Rauw Alejandro', year: 2021 },
    { name: 'El Teléfono', artist: 'Héctor El Father & Wisin & Yandel', year: 2006 },
    { name: 'Caile', artist: 'Tito El Bambino', year: 2005 },
    { name: 'Siente el Boom', artist: 'Tito El Bambino', year: 2007 },
    { name: 'El Amor', artist: 'Tito El Bambino', year: 2009 },
    { name: 'Mi Cama Huele a Ti', artist: 'Tito El Bambino', year: 2009 },
    { name: 'Flow Natural', artist: 'Tito El Bambino', year: 2006 },
    { name: 'Quiero Bailar', artist: 'Ivy Queen', year: 2003 },
    { name: 'Baila Morena', artist: 'Hector & Tito', year: 2002 },
    { name: 'Métele Sazón', artist: 'Tego Calderón', year: 2003 },
    { name: 'Machucando', artist: 'Daddy Yankee', year: 2005 },
    { name: 'Bandoleros', artist: 'Don Omar & Tego Calderón', year: 2005 },
    { name: 'Punto y Aparte', artist: 'Tego Calderón', year: 2004 },
    { name: 'Impacto', artist: 'Daddy Yankee', year: 2007 },
    { name: 'Zun Da Da', artist: 'Zion', year: 2007 },
    { name: 'Yo Voy', artist: 'Zion & Lennox', year: 2004 },
    { name: 'Doncella', artist: 'Zion & Lennox', year: 2004 },
    { name: 'Hay Algo en Ti', artist: 'Zion & Lennox', year: 2008 },
    { name: 'Otra Vez', artist: 'Zion & Lennox', year: 2016 },
    { name: 'Embriágame', artist: 'Zion & Lennox', year: 2016 },
    { name: 'La Player', artist: 'Zion & Lennox', year: 2018 },
    { name: 'Me Prefieres a Mí', artist: 'Arcángel', year: 2012 },
    { name: 'Hace Mucho Tiempo', artist: 'Arcángel', year: 2013 },
    { name: 'Pa Que la Pases Bien', artist: 'Arcángel', year: 2008 },
    { name: 'Por Amar a Ciegas', artist: 'Arcángel', year: 2008 },
    { name: 'Me Acostumbré', artist: 'Arcángel', year: 2017 },
    { name: 'Diles', artist: 'Bad Bunny', year: 2016 },
    { name: 'Soy Peor', artist: 'Bad Bunny', year: 2016 },
    { name: 'Chambea', artist: 'Bad Bunny', year: 2017 },
    { name: 'Amorfoda', artist: 'Bad Bunny', year: 2018 },
    { name: 'Estamos Bien', artist: 'Bad Bunny', year: 2018 },
    { name: 'Mía', artist: 'Bad Bunny', year: 2018 },
    { name: 'Callaita', artist: 'Bad Bunny', year: 2019 },
    { name: 'Safaera', artist: 'Bad Bunny', year: 2020 },
    { name: 'La Canción', artist: 'J Balvin & Bad Bunny', year: 2019 },
    { name: 'Qué Pretendes', artist: 'J Balvin & Bad Bunny', year: 2019 },
    { name: '6 AM', artist: 'J Balvin', year: 2013 },
    { name: 'Ginza', artist: 'J Balvin', year: 2015 },
    { name: 'Sigo Extrañándote', artist: 'J Balvin', year: 2016 },
    { name: 'Machika', artist: 'J Balvin', year: 2018 },
    { name: 'Reggaeton', artist: 'J Balvin', year: 2018 },
    { name: 'Loco Contigo', artist: 'DJ Snake, J Balvin & Tyga', year: 2019 },
    { name: 'Ella Quiere Beber', artist: 'Anuel AA', year: 2018 },
    { name: 'Amanece', artist: 'Anuel AA', year: 2018 },
    { name: 'Adicto', artist: 'Tainy, Anuel AA & Ozuna', year: 2019 },
    { name: 'Baila Baila Baila', artist: 'Ozuna', year: 2019 },
    { name: 'Se Preparó', artist: 'Ozuna', year: 2017 },
    { name: 'Dile Que Tú Me Quieres', artist: 'Ozuna', year: 2016 },
    { name: 'Síguelo Bailando', artist: 'Ozuna', year: 2017 },
    { name: 'Criminal', artist: 'Natti Natasha & Ozuna', year: 2017 },
    { name: 'Sin Pijama', artist: 'Becky G & Natti Natasha', year: 2018 },
    { name: 'Mayores', artist: 'Becky G', year: 2017 },
    { name: 'La Respuesta', artist: 'Becky G & Maluma', year: 2019 },
    { name: 'Soltera', artist: 'Lunay', year: 2019 },
    { name: 'A Solas', artist: 'Lunay', year: 2019 },
    { name: 'La Jeepeta', artist: 'Nio Garcia', year: 2020 },
    { name: 'Sensualidad', artist: 'Bad Bunny, Prince Royce & J Balvin', year: 2017 },
    { name: 'Vete', artist: 'Bad Bunny', year: 2019 },
    { name: 'Guaya Guaya', artist: 'Don Omar', year: 2015 },
    { name: 'Me Rehúso', artist: 'Danny Ocean', year: 2016 },
    { name: 'La Ocasión', artist: 'De La Ghetto, Arcángel & Ozuna', year: 2016 },
    { name: 'Down', artist: 'Rakim & Ken-Y', year: 2006 },
  ],
} satisfies Record<string, GenreSong[]>;
