type GenreSong = {
  name: string;
  artist: string;
  year: number;
};

export const EXTRA_GENRE_SONGS_LATIN = {
  'EDM': [
    { name: 'Spaceman', artist: 'Hardwell', year: 2012 },
    { name: 'Apollo', artist: 'Hardwell', year: 2012 },
    { name: 'Dare You', artist: 'Hardwell', year: 2013 },
    { name: 'Jumper', artist: 'Hardwell & W&W', year: 2013 },
    { name: 'Countdown', artist: 'Hardwell & MAKJ', year: 2013 },
    { name: 'Never Say Goodbye', artist: 'Hardwell & Dyro', year: 2013 },
    { name: 'Arcadia', artist: 'Hardwell & Joey Dale', year: 2014 },
    { name: 'Everybody Is in the Place', artist: 'Hardwell', year: 2014 },
    { name: 'Young Again', artist: 'Hardwell', year: 2014 },
    { name: 'Sally', artist: 'Hardwell', year: 2015 },
    { name: 'Follow Me', artist: 'Hardwell', year: 2015 },
    { name: 'Mad World', artist: 'Hardwell', year: 2015 },
    { name: 'United We Are', artist: 'Hardwell', year: 2015 },
    { name: 'Toulouse', artist: 'Nicky Romero', year: 2011 },
    { name: 'I Could Be the One', artist: 'Avicii & Nicky Romero', year: 2012 },
    { name: 'Legacy', artist: 'Nicky Romero & Krewella', year: 2013 },
    { name: 'Like Home', artist: 'Nicky Romero & NERVO', year: 2012 },
    { name: 'Symphonica', artist: 'Nicky Romero', year: 2013 },
    { name: 'Tremor', artist: 'Dimitri Vegas & Like Mike', year: 2014 },
    { name: 'Mammoth', artist: 'Dimitri Vegas & Like Mike', year: 2013 },
    { name: 'The Hum', artist: 'Dimitri Vegas & Like Mike', year: 2015 },
    { name: 'Wakanda', artist: 'Dimitri Vegas & Like Mike', year: 2013 },
    { name: 'Find Tomorrow', artist: 'Dimitri Vegas & Like Mike', year: 2013 },
    { name: 'Booyah', artist: 'Showtek', year: 2013 },
    { name: 'Cannonball', artist: 'Showtek & Justin Prime', year: 2012 },
    { name: 'We Like to Party', artist: 'Showtek', year: 2014 },
    { name: 'Bad', artist: 'David Guetta & Showtek', year: 2014 },
    { name: 'Sun Goes Down', artist: 'David Guetta & Showtek', year: 2014 },
    { name: 'How We Do', artist: 'Hardwell & Showtek', year: 2012 },
    { name: 'Cannonball Earthquake', artist: 'Showtek & Justin Prime', year: 2013 },
    { name: 'Helicopter', artist: 'Martin Garrix & Firebeatz', year: 2014 },
    { name: 'Wizard', artist: 'Martin Garrix & Jay Hardway', year: 2013 },
    { name: 'Tremor', artist: 'Martin Garrix & Dimitri Vegas & Like Mike', year: 2014 },
    { name: 'Proxy', artist: 'Martin Garrix', year: 2014 },
    { name: 'Virus', artist: 'Martin Garrix & MOTi', year: 2014 },
    { name: 'Gold Skies', artist: 'Sander van Doorn, Martin Garrix & DVBBS', year: 2014 },
    { name: 'Forbidden Voices', artist: 'Martin Garrix', year: 2015 },
    { name: 'The Only Way Is Up', artist: 'Martin Garrix & Tiësto', year: 2015 },
    { name: 'Secrets', artist: 'Tiësto & KSHMR', year: 2015 },
    { name: 'Maximal Crazy', artist: 'Tiësto', year: 2011 },
    { name: 'Chasing Summers', artist: 'Tiësto', year: 2012 },
    { name: 'Adagio for Strings', artist: 'Tiësto', year: 2005 },
    { name: 'Zero 76', artist: 'Tiësto & Hardwell', year: 2011 },
    { name: 'Split', artist: 'Tiësto & The Chainsmokers', year: 2015 },
    { name: 'Turn Up the Speakers', artist: 'Afrojack & Martin Garrix', year: 2014 },
    { name: 'Ten Feet Tall', artist: 'Afrojack', year: 2014 },
    { name: 'The Spark', artist: 'Afrojack', year: 2013 },
    { name: 'Take Over Control', artist: 'Afrojack', year: 2010 },
    { name: 'As Your Friend', artist: 'Afrojack', year: 2013 },
    { name: 'No Beef', artist: 'Afrojack & Steve Aoki', year: 2011 },
    { name: 'Boneless', artist: 'Steve Aoki, Chris Lake & Tujamo', year: 2013 },
    { name: 'Delirious', artist: 'Steve Aoki', year: 2014 },
    { name: 'Rage the Night Away', artist: 'Steve Aoki', year: 2014 },
    { name: 'A Light That Never Comes', artist: 'Steve Aoki & Linkin Park', year: 2013 },
    { name: 'Turbulence', artist: 'Steve Aoki & Laidback Luke', year: 2011 },
    { name: 'Beat Down', artist: 'Steve Aoki & Angger Dimas', year: 2012 },
    { name: 'Get Me Outta Here', artist: 'Steve Aoki & Flux Pavilion', year: 2014 },
    { name: 'Born to Get Wild', artist: 'Steve Aoki', year: 2014 },
    { name: 'Ladi Dadi', artist: 'Steve Aoki', year: 2012 },
    { name: 'Stampede', artist: 'Dimitri Vegas & Like Mike, Borgeous & DVBBS', year: 2013 },
    { name: 'Tsunami', artist: 'DVBBS & Borgeous', year: 2013 },
    { name: 'Invincible', artist: 'Borgeous', year: 2014 },
    { name: 'Wildfire', artist: 'Borgeous', year: 2014 },
    { name: 'Bigfoot', artist: 'W&W', year: 2014 },
    { name: 'The Code', artist: 'W&W & Ummet Ozcan', year: 2013 },
    { name: 'Thunder', artist: 'W&W', year: 2013 },
    { name: 'Rocket', artist: 'W&W & Blasterjaxx', year: 2014 },
    { name: 'Rave After Rave', artist: 'W&W', year: 2015 },
    { name: 'This Is What It Feels Like', artist: 'Armin van Buuren', year: 2013 },
    { name: 'Ping Pong', artist: 'Armin van Buuren', year: 2014 },
    { name: 'Save My Night', artist: 'Armin van Buuren', year: 2014 },
    { name: 'Another You', artist: 'Armin van Buuren', year: 2015 },
    { name: 'Beautiful Life', artist: 'Armin van Buuren', year: 2013 },
    { name: 'Intense', artist: 'Armin van Buuren', year: 2013 },
    { name: 'If I Lose Myself', artist: 'Alesso vs OneRepublic', year: 2013 },
    { name: 'Heroes', artist: 'Alesso', year: 2014 },
    { name: 'Under Control', artist: 'Calvin Harris & Alesso', year: 2013 },
    { name: 'Years', artist: 'Alesso', year: 2012 },
    { name: 'Calling', artist: 'Sebastian Ingrosso & Alesso', year: 2012 },
    { name: 'Reload', artist: 'Sebastian Ingrosso & Tommy Trash', year: 2012 },
    { name: 'Center of the Universe', artist: 'Axwell', year: 2013 },
    { name: 'I Am', artist: 'Axwell', year: 2013 },
    { name: 'Sun Is Shining', artist: 'Axwell Λ Ingrosso', year: 2015 },
    { name: 'Something New', artist: 'Axwell Λ Ingrosso', year: 2014 },
    { name: 'Heroes', artist: 'Måns Zelmerlöw', year: 2015 },
    { name: 'Eat Sleep Rave Repeat', artist: 'Fatboy Slim & Riva Starr', year: 2013 },
    { name: 'Turn Down for What', artist: 'DJ Snake & Lil Jon', year: 2013 },
    { name: 'Get Low', artist: 'Dillon Francis & DJ Snake', year: 2014 },
    { name: 'You Know You Like It', artist: 'DJ Snake & AlunaGeorge', year: 2014 },
    { name: 'Middle', artist: 'DJ Snake', year: 2015 },
    { name: 'Lovers on the Sun', artist: 'David Guetta', year: 2014 },
    { name: 'Shot Me Down', artist: 'David Guetta', year: 2014 },
    { name: 'Play Hard', artist: 'David Guetta', year: 2012 },
    { name: 'She Wolf', artist: 'David Guetta', year: 2012 },
    { name: 'Bad', artist: 'David Guetta', year: 2014 },
    { name: 'Lunar', artist: 'David Guetta & Afrojack', year: 2011 },
    { name: 'Hey Mama', artist: 'David Guetta', year: 2015 },
    { name: 'Sweet Nothing', artist: 'Calvin Harris', year: 2012 },
    { name: 'Outside', artist: 'Calvin Harris', year: 2014 },
    { name: 'Blame', artist: 'Calvin Harris', year: 2014 },
  ],
  'Pop Latino': [
    { name: 'Color Esperanza', artist: 'Diego Torres', year: 2001 },
    { name: 'Tratar de Estar Mejor', artist: 'Diego Torres', year: 1994 },
    { name: 'Penélope', artist: 'Diego Torres', year: 1996 },
    { name: 'Sueños', artist: 'Diego Torres', year: 2004 },
    { name: 'Creo en América', artist: 'Diego Torres', year: 2011 },
    { name: 'Corazón Partío', artist: 'Alejandro Sanz', year: 1997 },
    { name: 'Amiga Mía', artist: 'Alejandro Sanz', year: 1997 },
    { name: 'Y Si Fuera Ella', artist: 'Alejandro Sanz', year: 1997 },
    { name: 'No Es lo Mismo', artist: 'Alejandro Sanz', year: 2003 },
    { name: 'Mi Persona Favorita', artist: 'Alejandro Sanz', year: 2019 },
    { name: 'Darte un Beso', artist: 'Prince Royce', year: 2013 },
    { name: 'Stand by Me', artist: 'Prince Royce', year: 2010 },
    { name: 'Corazón Sin Cara', artist: 'Prince Royce', year: 2010 },
    { name: 'Las Cosas Pequeñas', artist: 'Prince Royce', year: 2012 },
    { name: 'Incondicional', artist: 'Prince Royce', year: 2012 },
    { name: 'El Amor Que Perdimos', artist: 'Prince Royce', year: 2010 },
    { name: 'Propuesta Indecente', artist: 'Romeo Santos', year: 2013 },
    { name: 'Eres Mía', artist: 'Romeo Santos', year: 2014 },
    { name: 'Odio', artist: 'Romeo Santos', year: 2014 },
    { name: 'Imitadora', artist: 'Romeo Santos', year: 2017 },
    { name: 'Sobredosis', artist: 'Romeo Santos', year: 2017 },
    { name: 'Bachata Rosa', artist: 'Juan Luis Guerra', year: 1990 },
    { name: 'Frío Frío', artist: 'Juan Luis Guerra', year: 1992 },
    { name: 'Visa Para un Sueño', artist: 'Juan Luis Guerra', year: 1989 },
    { name: 'El Niágara en Bicicleta', artist: 'Juan Luis Guerra', year: 1998 },
    { name: 'La Llave de Mi Corazón', artist: 'Juan Luis Guerra', year: 2007 },
    { name: 'Bachata en Fukuoka', artist: 'Juan Luis Guerra', year: 2010 },
    { name: 'La Gozadera', artist: 'Gente de Zona', year: 2015 },
    { name: 'Traidora', artist: 'Gente de Zona', year: 2015 },
    { name: 'Más Macarena', artist: 'Gente de Zona', year: 2016 },
    { name: 'Si No Vuelves', artist: 'Gente de Zona', year: 2016 },
    { name: 'Bailando', artist: 'Gente de Zona', year: 2014 },
    { name: 'La Mordidita', artist: 'Ricky Martin', year: 2015 },
    { name: 'Vente Pa Ca', artist: 'Ricky Martin', year: 2016 },
    { name: 'Tal Vez', artist: 'Ricky Martin', year: 2003 },
    { name: 'Tu Recuerdo', artist: 'Ricky Martin', year: 2006 },
    { name: 'Disparo al Corazón', artist: 'Ricky Martin', year: 2015 },
    { name: 'Adrenalina', artist: 'Wisin', year: 2014 },
    { name: 'Nota de Amor', artist: 'Wisin', year: 2015 },
    { name: 'Que Viva la Vida', artist: 'Wisin', year: 2013 },
    { name: 'Duele el Corazón', artist: 'Enrique Iglesias', year: 2016 },
    { name: 'Súbeme la Radio', artist: 'Enrique Iglesias', year: 2017 },
    { name: 'Tonight', artist: 'Enrique Iglesias', year: 2010 },
    { name: 'I Like It', artist: 'Enrique Iglesias', year: 2010 },
    { name: 'Cuando Me Enamoro', artist: 'Enrique Iglesias', year: 2010 },
    { name: 'Me Pasé', artist: 'Enrique Iglesias', year: 2021 },
    { name: 'Rabiosa', artist: 'Shakira', year: 2010 },
    { name: 'Addicted to You', artist: 'Shakira', year: 2012 },
    { name: 'Me Enamoré', artist: 'Shakira', year: 2017 },
    { name: 'Chantaje', artist: 'Shakira', year: 2016 },
    { name: 'Las de la Intuición', artist: 'Shakira', year: 2005 },
    { name: 'Día de Enero', artist: 'Shakira', year: 2005 },
    { name: 'Suerte', artist: 'Shakira', year: 2001 },
    { name: 'Estoy Aquí', artist: 'Shakira', year: 1995 },
    { name: 'Antología', artist: 'Shakira', year: 1995 },
    { name: 'Ojos Así', artist: 'Shakira', year: 1998 },
    { name: 'Me Voy', artist: 'Julieta Venegas', year: 2006 },
    { name: 'Limón y Sal', artist: 'Julieta Venegas', year: 2006 },
    { name: 'Eres Para Mí', artist: 'Julieta Venegas', year: 2006 },
    { name: 'Andar Conmigo', artist: 'Julieta Venegas', year: 2003 },
    { name: 'Lento', artist: 'Julieta Venegas', year: 2003 },
    { name: 'Fotografía', artist: 'Juanes', year: 2002 },
    { name: 'Volverte a Ver', artist: 'Juanes', year: 2004 },
    { name: 'Nada Valgo Sin Tu Amor', artist: 'Juanes', year: 2004 },
    { name: 'Es Por Ti', artist: 'Juanes', year: 2002 },
    { name: 'Yerbatero', artist: 'Juanes', year: 2010 },
    { name: 'La Luz', artist: 'Juanes', year: 2013 },
    { name: 'Fruta Fresca', artist: 'Carlos Vives', year: 1999 },
    { name: 'Volví a Nacer', artist: 'Carlos Vives', year: 2012 },
    { name: 'Robarte un Beso', artist: 'Carlos Vives', year: 2017 },
    { name: 'Nota de Amor', artist: 'Carlos Vives', year: 2015 },
    { name: 'Cuando Nos Volvamos a Encontrar', artist: 'Carlos Vives', year: 2014 },
    { name: 'Colgando en Tus Manos', artist: 'Carlos Baute', year: 2008 },
    { name: 'Quién Te Quiere Como Yo', artist: 'Carlos Baute', year: 2010 },
    { name: 'Te Regalo', artist: 'Carlos Baute', year: 2005 },
    { name: 'Yo Quisiera', artist: 'Reik', year: 2005 },
    { name: 'Noviembre Sin Ti', artist: 'Reik', year: 2005 },
    { name: 'Me Niego', artist: 'Reik', year: 2018 },
    { name: 'Creo en Ti', artist: 'Reik', year: 2011 },
    { name: 'Ya Me Enteré', artist: 'Reik', year: 2016 },
    { name: 'Kilómetros', artist: 'Sin Bandera', year: 2002 },
    { name: 'Entra en Mi Vida', artist: 'Sin Bandera', year: 2002 },
    { name: 'Suelta Mi Mano', artist: 'Sin Bandera', year: 2005 },
    { name: 'Que Lloro', artist: 'Sin Bandera', year: 2003 },
    { name: 'Mientes Tan Bien', artist: 'Sin Bandera', year: 2003 },
    { name: 'Todo Cambió', artist: 'Camila', year: 2006 },
    { name: 'Mientes', artist: 'Camila', year: 2010 },
    { name: 'Aléjate de Mí', artist: 'Camila', year: 2010 },
    { name: 'Abrázame', artist: 'Camila', year: 2006 },
    { name: 'Coleccionista de Canciones', artist: 'Camila', year: 2006 },
    { name: 'Corre', artist: 'Jesse & Joy', year: 2011 },
    { name: 'Espacio Sideral', artist: 'Jesse & Joy', year: 2006 },
    { name: 'Dueles', artist: 'Jesse & Joy', year: 2015 },
    { name: 'La de la Mala Suerte', artist: 'Jesse & Joy', year: 2011 },
    { name: 'Ecos de Amor', artist: 'Jesse & Joy', year: 2015 },
    { name: 'Tú', artist: 'Noelia', year: 1999 },
    { name: 'Mi Mayor Anhelo', artist: 'Banda MS', year: 2012 },
    { name: 'Solo Con Verte', artist: 'Banda MS', year: 2015 },
    { name: 'Calma', artist: 'Pedro Capó', year: 2018 },
  ],
  'Reggaetón': [
    { name: 'Lo Que Pasó Pasó', artist: 'Daddy Yankee', year: 2004 },
    { name: 'Rompe', artist: 'Daddy Yankee', year: 2005 },
    { name: 'Ella Me Levantó', artist: 'Daddy Yankee', year: 2007 },
    { name: 'Pose', artist: 'Daddy Yankee', year: 2008 },
    { name: 'Llamado de Emergencia', artist: 'Daddy Yankee', year: 2008 },
    { name: 'La Despedida', artist: 'Daddy Yankee', year: 2010 },
    { name: 'Lovumba', artist: 'Daddy Yankee', year: 2011 },
    { name: 'Dura', artist: 'Daddy Yankee', year: 2018 },
    { name: 'Que Tire Pa Lante', artist: 'Daddy Yankee', year: 2019 },
    { name: 'Mayor Que Yo', artist: 'Baby Ranks', year: 2005 },
    { name: 'Noche de Sexo', artist: 'Wisin & Yandel', year: 2005 },
    { name: 'Pam Pam', artist: 'Wisin & Yandel', year: 2006 },
    { name: 'Sexy Movimiento', artist: 'Wisin & Yandel', year: 2007 },
    { name: 'Abusadora', artist: 'Wisin & Yandel', year: 2009 },
    { name: 'Me Estás Tentando', artist: 'Wisin & Yandel', year: 2008 },
    { name: 'Algo Me Gusta de Ti', artist: 'Wisin & Yandel', year: 2012 },
    { name: 'Noche de Entierro', artist: 'Los Benjamins', year: 2006 },
    { name: 'Mayor Que Yo 3', artist: 'Luny Tunes', year: 2015 },
    { name: 'Mayor Que Yo 2', artist: 'Luny Tunes', year: 2010 },
    { name: 'Dile', artist: 'Don Omar', year: 2003 },
    { name: 'Pobre Diabla', artist: 'Don Omar', year: 2003 },
    { name: 'Dale Don Dale', artist: 'Don Omar', year: 2003 },
    { name: 'Salió el Sol', artist: 'Don Omar', year: 2006 },
    { name: 'Taboo', artist: 'Don Omar', year: 2011 },
    { name: 'Hasta Abajo', artist: 'Don Omar', year: 2009 },
    { name: 'Zumba', artist: 'Don Omar', year: 2012 },
    { name: 'Danza Kuduro', artist: 'Lucenzo', year: 2010 },
    { name: 'Ven Báilalo', artist: 'Angel y Khriz', year: 2004 },
    { name: 'Na De Na', artist: 'Angel y Khriz', year: 2008 },
    { name: 'Carita de Ángel', artist: 'Erre XI', year: 2008 },
    { name: 'Nena', artist: 'Miguelito', year: 2006 },
    { name: 'Guatauba', artist: 'Plan B', year: 2002 },
    { name: 'Si No Le Contesto', artist: 'Plan B', year: 2010 },
    { name: 'Fanática Sensual', artist: 'Plan B', year: 2014 },
    { name: 'Candy', artist: 'Plan B', year: 2014 },
    { name: 'Mi Vecinita', artist: 'Plan B', year: 2014 },
    { name: 'Te Dijeron', artist: 'Plan B', year: 2014 },
    { name: 'Me Niegas', artist: 'Baby Rasta & Gringo', year: 2013 },
    { name: 'Un Beso', artist: 'Aventura', year: 2005 },
    { name: 'Noche de Travesura', artist: 'Héctor El Father', year: 2005 },
    { name: 'Sola', artist: 'Héctor El Father', year: 2006 },
    { name: 'Déjale Caer To el Peso', artist: 'Héctor El Father', year: 2006 },
    { name: 'El Teléfono', artist: 'Héctor El Father & Wisin & Yandel', year: 2006 },
    { name: 'Caile', artist: 'Tito El Bambino', year: 2005 },
    { name: 'Siente el Boom', artist: 'Tito El Bambino', year: 2007 },
    { name: 'El Amor', artist: 'Tito El Bambino', year: 2009 },
    { name: 'Mi Cama Huele a Ti', artist: 'Tito El Bambino', year: 2009 },
    { name: 'Flow Natural', artist: 'Tito El Bambino', year: 2006 },
    { name: 'Felina', artist: 'Hector & Tito', year: 2002 },
    { name: 'Baila Morena', artist: 'Hector & Tito', year: 2002 },
    { name: 'Métele Sazón', artist: 'Tego Calderón', year: 2003 },
    { name: 'Pa Que Retozen', artist: 'Tego Calderón', year: 2003 },
    { name: 'Guasa Guasa', artist: 'Tego Calderón', year: 2003 },
    { name: 'Punto y Aparte', artist: 'Tego Calderón', year: 2004 },
    { name: 'Elegante de Boutique', artist: 'Tego Calderón', year: 2008 },
    { name: 'Zun Da Da', artist: 'Zion', year: 2007 },
    { name: 'Yo Voy', artist: 'Zion & Lennox', year: 2004 },
    { name: 'Doncella', artist: 'Zion & Lennox', year: 2004 },
    { name: 'Hay Algo en Ti', artist: 'Zion & Lennox', year: 2008 },
    { name: 'Otra Vez', artist: 'Zion & Lennox', year: 2016 },
    { name: 'Embriágame', artist: 'Zion & Lennox', year: 2016 },
    { name: 'La Player', artist: 'Zion & Lennox', year: 2018 },
    { name: 'Me Prefieres a Mí', artist: 'Arcángel', year: 2012 },
    { name: 'Hace Mucho Tiempo', artist: 'Arcángel', year: 2013 },
    { name: 'Pa Que la Pases Bien', artist: 'Arcángel', year: 2008 },
    { name: 'Por Amar a Ciegas', artist: 'Arcángel', year: 2008 },
    { name: 'Me Acostumbré', artist: 'Arcángel', year: 2017 },
    { name: 'Diles', artist: 'Bad Bunny', year: 2016 },
    { name: 'Soy Peor', artist: 'Bad Bunny', year: 2016 },
    { name: 'Chambea', artist: 'Bad Bunny', year: 2017 },
    { name: 'Amorfoda', artist: 'Bad Bunny', year: 2018 },
    { name: 'Estamos Bien', artist: 'Bad Bunny', year: 2018 },
    { name: 'Mía', artist: 'Bad Bunny', year: 2018 },
    { name: 'Callaita', artist: 'Bad Bunny', year: 2019 },
    { name: 'Safaera', artist: 'Bad Bunny', year: 2020 },
    { name: 'La Canción', artist: 'J Balvin & Bad Bunny', year: 2019 },
    { name: 'Qué Pretendes', artist: 'J Balvin & Bad Bunny', year: 2019 },
    { name: '6 AM', artist: 'J Balvin', year: 2013 },
    { name: 'Ginza', artist: 'J Balvin', year: 2015 },
    { name: 'Sigo Extrañándote', artist: 'J Balvin', year: 2016 },
    { name: 'Machika', artist: 'J Balvin', year: 2018 },
    { name: 'Reggaeton', artist: 'J Balvin', year: 2018 },
    { name: 'Loco Contigo', artist: 'DJ Snake, J Balvin & Tyga', year: 2019 },
    { name: 'Ella Quiere Beber', artist: 'Anuel AA', year: 2018 },
    { name: 'Amanece', artist: 'Anuel AA', year: 2018 },
    { name: 'Adicto', artist: 'Tainy, Anuel AA & Ozuna', year: 2019 },
    { name: 'Baila Baila Baila', artist: 'Ozuna', year: 2019 },
    { name: 'Se Preparó', artist: 'Ozuna', year: 2017 },
    { name: 'Dile Que Tú Me Quieres', artist: 'Ozuna', year: 2016 },
    { name: 'Síguelo Bailando', artist: 'Ozuna', year: 2017 },
    { name: 'Criminal', artist: 'Natti Natasha & Ozuna', year: 2017 },
    { name: 'Sin Pijama', artist: 'Becky G & Natti Natasha', year: 2018 },
    { name: 'Mayores', artist: 'Becky G', year: 2017 },
    { name: 'La Respuesta', artist: 'Becky G & Maluma', year: 2019 },
    { name: 'Soltera', artist: 'Lunay', year: 2019 },
    { name: 'A Solas', artist: 'Lunay', year: 2019 },
    { name: 'La Jeepeta', artist: 'Nio Garcia', year: 2020 },
    { name: 'Shaky Shaky', artist: 'Daddy Yankee', year: 2016 },
    { name: 'Ay Vamos', artist: 'J Balvin', year: 2014 },
    { name: 'Guaya Guaya', artist: 'Don Omar', year: 2015 },
    { name: 'Si No Le Contesto', artist: 'Plan B', year: 2010 },
    { name: 'Noche de Entierro', artist: 'Los Benjamins', year: 2006 },
    { name: 'Down', artist: 'Rakim & Ken-Y', year: 2006 },
  ],
} satisfies Record<string, GenreSong[]>;
