type GenreSong = {
  name: string;
  artist: string;
  year: number;
};

export const EXTRA_GENRE_SONGS_LATIN = {
  'EDM': [
    { name: 'Spaceman', artist: 'Hardwell', year: 2012 },
    { name: 'Apollo', artist: 'Hardwell', year: 2012 },
    { name: 'Dare You', artist: 'Hardwell', year: 2013 },
    { name: 'Jumper', artist: 'Hardwell & W&W', year: 2013 },
    { name: 'Countdown', artist: 'Hardwell & MAKJ', year: 2013 },
    { name: 'Never Say Goodbye', artist: 'Hardwell & Dyro', year: 2013 },
    { name: 'Language', artist: 'Porter Robinson', year: 2012 },
    { name: 'Easy', artist: 'Mat Zo & Porter Robinson', year: 2013 },
    { name: 'Runaway (U & I)', artist: 'Galantis', year: 2014 },
    { name: 'Peanut Butter Jelly', artist: 'Galantis', year: 2015 },
    { name: 'I Love It', artist: 'Icona Pop', year: 2012 },
    { name: 'Toulouse', artist: 'Nicky Romero', year: 2011 },
    { name: 'I Could Be the One', artist: 'Avicii & Nicky Romero', year: 2012 },
    { name: 'Legacy', artist: 'Nicky Romero & Krewella', year: 2013 },
    { name: 'Like Home', artist: 'Nicky Romero & NERVO', year: 2012 },
    { name: 'Symphonica', artist: 'Nicky Romero', year: 2013 },
    { name: 'Tremor', artist: 'Dimitri Vegas & Like Mike', year: 2014 },
    { name: 'Mammoth', artist: 'Dimitri Vegas & Like Mike', year: 2013 },
    { name: 'The Hum', artist: 'Dimitri Vegas & Like Mike', year: 2015 },
    { name: 'Waves', artist: 'Mr. Probz', year: 2014 },
    { name: 'Booyah', artist: 'Showtek', year: 2013 },
    { name: 'Cannonball', artist: 'Showtek & Justin Prime', year: 2012 },
    { name: 'We Like to Party', artist: 'Showtek', year: 2014 },
    { name: 'Bad', artist: 'David Guetta & Showtek', year: 2014 },
    { name: 'How We Do', artist: 'Hardwell & Showtek', year: 2012 },
    { name: 'Cheerleader', artist: 'OMI', year: 2014 },
    { name: 'Helicopter', artist: 'Martin Garrix & Firebeatz', year: 2014 },
    { name: 'Wizard', artist: 'Martin Garrix & Jay Hardway', year: 2013 },
    { name: 'Tremor', artist: 'Martin Garrix & Dimitri Vegas & Like Mike', year: 2014 },
    { name: 'Gold Skies', artist: 'Sander van Doorn, Martin Garrix & DVBBS', year: 2014 },
    { name: 'C\'Mon', artist: 'Tiësto & Diplo', year: 2010 },
    { name: 'Adagio for Strings', artist: 'Tiësto', year: 2005 },
    { name: 'Zero 76', artist: 'Tiësto & Hardwell', year: 2011 },
    { name: 'Secrets', artist: 'Tiësto & KSHMR', year: 2015 },
    { name: 'Turn Up the Speakers', artist: 'Afrojack & Martin Garrix', year: 2014 },
    { name: 'Ten Feet Tall', artist: 'Afrojack', year: 2014 },
    { name: 'The Spark', artist: 'Afrojack', year: 2013 },
    { name: 'Take Over Control', artist: 'Afrojack', year: 2010 },
    { name: 'No Beef', artist: 'Afrojack & Steve Aoki', year: 2011 },
    { name: 'Boneless', artist: 'Steve Aoki, Chris Lake & Tujamo', year: 2013 },
    { name: 'Delirious', artist: 'Steve Aoki', year: 2014 },
    { name: 'Rage the Night Away', artist: 'Steve Aoki', year: 2014 },
    { name: 'A Light That Never Comes', artist: 'Steve Aoki & Linkin Park', year: 2013 },
    { name: 'Turbulence', artist: 'Steve Aoki & Laidback Luke', year: 2011 },
    { name: 'Pursuit of Happiness', artist: 'Kid Cudi & Steve Aoki', year: 2012 },
    { name: 'Just Hold On', artist: 'Steve Aoki & Louis Tomlinson', year: 2016 },
    { name: 'Waste It On Me', artist: 'Steve Aoki & BTS', year: 2018 },
    { name: 'Azukita', artist: 'Steve Aoki, Daddy Yankee & Play-N-Skillz', year: 2018 },
    { name: 'Stampede', artist: 'Dimitri Vegas & Like Mike, Borgeous & DVBBS', year: 2013 },
    { name: 'Tsunami', artist: 'DVBBS & Borgeous', year: 2013 },
    { name: 'Five Hours', artist: 'Deorro', year: 2014 },
    { name: 'Five More Hours', artist: 'Deorro & Chris Brown', year: 2015 },
    { name: 'Bigfoot', artist: 'W&W', year: 2014 },
    { name: 'The Code', artist: 'W&W & Ummet Ozcan', year: 2013 },
    { name: 'Thunder', artist: 'W&W', year: 2013 },
    { name: 'Rocket', artist: 'W&W & Blasterjaxx', year: 2014 },
    { name: 'Beautiful World', artist: 'Blasterjaxx & DBSTF', year: 2015 },
    { name: 'This Is What It Feels Like', artist: 'Armin van Buuren', year: 2013 },
    { name: 'Ping Pong', artist: 'Armin van Buuren', year: 2014 },
    { name: 'Not Giving Up On Love', artist: 'Armin van Buuren', year: 2010 },
    { name: 'If I Lose Myself', artist: 'Alesso vs OneRepublic', year: 2013 },
    { name: 'Heroes', artist: 'Alesso', year: 2014 },
    { name: 'Under Control', artist: 'Calvin Harris & Alesso', year: 2013 },
    { name: 'Years', artist: 'Alesso', year: 2012 },
    { name: 'Calling', artist: 'Sebastian Ingrosso & Alesso', year: 2012 },
    { name: 'Reload', artist: 'Sebastian Ingrosso & Tommy Trash', year: 2012 },
    { name: 'Center of the Universe', artist: 'Axwell', year: 2013 },
    { name: 'Resurrection', artist: 'Michael Calfan', year: 2011 },
    { name: 'Sun Is Shining', artist: 'Axwell Λ Ingrosso', year: 2015 },
    { name: 'Something New', artist: 'Axwell Λ Ingrosso', year: 2014 },
    { name: 'Gold Dust', artist: 'Galantis', year: 2015 },
    { name: 'Eat Sleep Rave Repeat', artist: 'Fatboy Slim & Riva Starr', year: 2013 },
    { name: 'Turn Down for What', artist: 'DJ Snake & Lil Jon', year: 2013 },
    { name: 'Get Low', artist: 'Dillon Francis & DJ Snake', year: 2014 },
    { name: 'You Know You Like It', artist: 'DJ Snake & AlunaGeorge', year: 2014 },
    { name: 'Middle', artist: 'DJ Snake', year: 2015 },
    { name: 'Call on Me', artist: 'Eric Prydz', year: 2004 },
    { name: 'Satisfaction', artist: 'Benny Benassi', year: 2002 },
    { name: '9 PM (Till I Come)', artist: 'ATB', year: 1998 },
    { name: 'Children', artist: 'Robert Miles', year: 1995 },
    { name: 'Insomnia', artist: 'Faithless', year: 1995 },
    { name: 'Porcelain', artist: 'Moby', year: 1999 },
    { name: 'Firestarter', artist: 'The Prodigy', year: 1996 },
    { name: 'Breathe', artist: 'The Prodigy', year: 1996 },
    { name: 'Praise You', artist: 'Fatboy Slim', year: 1998 },
    { name: 'Right Here, Right Now', artist: 'Fatboy Slim', year: 1999 },
    { name: 'Ocean Drive', artist: 'Duke Dumont', year: 2015 },
    { name: 'Fast Car', artist: 'Jonas Blue', year: 2015 },
    { name: 'Sugar', artist: 'Robin Schulz', year: 2015 },
    { name: 'Are You With Me', artist: 'Lost Frequencies', year: 2014 },
    { name: 'Easy Love', artist: 'Sigala', year: 2015 },
    { name: 'This Girl', artist: 'Kungs', year: 2016 },
    { name: "You Don't Know Me", artist: 'Jax Jones', year: 2016 },
    { name: 'Feel the Love', artist: 'Rudimental', year: 2012 },
    { name: 'Waiting All Night', artist: 'Rudimental', year: 2013 },
    { name: 'Latch', artist: 'Disclosure', year: 2012 },
    { name: 'White Noise', artist: 'Disclosure', year: 2013 },
    { name: 'Never Be Like You', artist: 'Flume', year: 2016 },
    { name: 'Alive', artist: 'Krewella', year: 2013 },
    { name: 'Cry (Just a Little)', artist: 'Bingo Players', year: 2011 },
    { name: 'Gecko', artist: 'Oliver Heldens', year: 2014 },
    { name: 'Nobody to Love', artist: 'Sigma', year: 2014 },
    { name: 'Ready for Your Love', artist: 'Gorgon City', year: 2014 },
    { name: 'My Love', artist: 'Route 94', year: 2013 },
    { name: 'Heroes (We Could Be)', artist: 'Alesso', year: 2014 },
    { name: 'Happier', artist: 'Marshmello', year: 2018 },
    { name: 'Darkside', artist: 'Alan Walker', year: 2018 },
    { name: 'Symphony', artist: 'Clean Bandit', year: 2017 },
    { name: 'Rockabye', artist: 'Clean Bandit', year: 2016 },
    { name: 'Scary Monsters and Nice Sprites', artist: 'Skrillex', year: 2010 },
    { name: 'Strobe', artist: 'Deadmau5', year: 2009 },
  ],
  'Pop Latino': [
    { name: 'Color Esperanza', artist: 'Diego Torres', year: 2001 },
    { name: 'Tratar de Estar Mejor', artist: 'Diego Torres', year: 1994 },
    { name: 'Sueños', artist: 'Diego Torres', year: 2004 },
    { name: 'Corazón Partío', artist: 'Alejandro Sanz', year: 1997 },
    { name: 'Amiga Mía', artist: 'Alejandro Sanz', year: 1997 },
    { name: 'No Es lo Mismo', artist: 'Alejandro Sanz', year: 2003 },
    { name: 'Darte un Beso', artist: 'Prince Royce', year: 2013 },
    { name: 'Stand by Me', artist: 'Prince Royce', year: 2010 },
    { name: 'Corazón Sin Cara', artist: 'Prince Royce', year: 2010 },
    { name: 'Propuesta Indecente', artist: 'Romeo Santos', year: 2013 },
    { name: 'Eres Mía', artist: 'Romeo Santos', year: 2014 },
    { name: 'Imitadora', artist: 'Romeo Santos', year: 2017 },
    { name: 'La Gozadera', artist: 'Gente de Zona', year: 2015 },
    { name: 'Traidora', artist: 'Gente de Zona', year: 2015 },
    { name: 'Bailando', artist: 'Gente de Zona', year: 2014 },
    { name: 'Adrenalina', artist: 'Wisin', year: 2014 },
    { name: 'Nota de Amor', artist: 'Wisin', year: 2015 },
    { name: 'Que Viva la Vida', artist: 'Wisin', year: 2013 },
    { name: 'Me Voy', artist: 'Julieta Venegas', year: 2006 },
    { name: 'Limón y Sal', artist: 'Julieta Venegas', year: 2006 },
    { name: 'Andar Conmigo', artist: 'Julieta Venegas', year: 2003 },
    { name: 'Fotografía', artist: 'Juanes', year: 2002 },
    { name: 'Fruta Fresca', artist: 'Carlos Vives', year: 1999 },
    { name: 'Robarte un Beso', artist: 'Carlos Vives', year: 2017 },
    { name: 'Colgando en Tus Manos', artist: 'Carlos Baute', year: 2008 },
    { name: 'Quién Te Quiere Como Yo', artist: 'Carlos Baute', year: 2010 },
    { name: 'Te Regalo', artist: 'Carlos Baute', year: 2005 },
    { name: 'Yo Quisiera', artist: 'Reik', year: 2005 },
    { name: 'Noviembre Sin Ti', artist: 'Reik', year: 2005 },
    { name: 'Me Niego', artist: 'Reik', year: 2018 },
    { name: 'Kilómetros', artist: 'Sin Bandera', year: 2002 },
    { name: 'Entra en Mi Vida', artist: 'Sin Bandera', year: 2002 },
    { name: 'Mientes Tan Bien', artist: 'Sin Bandera', year: 2003 },
    { name: 'Todo Cambió', artist: 'Camila', year: 2006 },
    { name: 'Mientes', artist: 'Camila', year: 2010 },
    { name: 'Aléjate de Mí', artist: 'Camila', year: 2010 },
    { name: 'Corre', artist: 'Jesse & Joy', year: 2011 },
    { name: 'Espacio Sideral', artist: 'Jesse & Joy', year: 2006 },
    { name: 'La de la Mala Suerte', artist: 'Jesse & Joy', year: 2011 },
    { name: 'Tú', artist: 'Noelia', year: 1999 },
    { name: 'Mi Mayor Anhelo', artist: 'Banda MS', year: 2012 },
    { name: 'Solo Con Verte', artist: 'Banda MS', year: 2015 },
    { name: 'Calma', artist: 'Pedro Capó', year: 2018 },
    { name: 'La Incondicional', artist: 'Luis Miguel', year: 1989 },
    { name: 'Ahora Te Puedes Marchar', artist: 'Luis Miguel', year: 1987 },
    { name: 'Suave', artist: 'Luis Miguel', year: 1993 },
    { name: 'Querida', artist: 'Juan Gabriel', year: 1984 },
    { name: 'Hasta Que Te Conocí', artist: 'Juan Gabriel', year: 1986 },
    { name: 'No Tengo Dinero', artist: 'Juan Gabriel', year: 1971 },
    { name: 'El Triste', artist: 'José José', year: 1970 },
    { name: 'Gavilán o Paloma', artist: 'José José', year: 1976 },
    { name: 'Amar y Querer', artist: 'José José', year: 1977 },
    { name: 'Amor Eterno', artist: 'Rocío Dúrcal', year: 1984 },
    { name: 'La Gata Bajo la Lluvia', artist: 'Rocío Dúrcal', year: 1981 },
    { name: 'Volver, Volver', artist: 'Vicente Fernández', year: 1976 },
    { name: 'El Rey', artist: 'Vicente Fernández', year: 1971 },
    { name: 'Por Tu Maldito Amor', artist: 'Vicente Fernández', year: 1989 },
    { name: 'Como Quien Pierde una Estrella', artist: 'Alejandro Fernández', year: 1996 },
    { name: 'Si Tú Supieras', artist: 'Alejandro Fernández', year: 1997 },
    { name: 'Me Dediqué a Perderte', artist: 'Alejandro Fernández', year: 2002 },
    { name: 'Te Amo', artist: 'Franco De Vita', year: 1988 },
    { name: 'No Basta', artist: 'Franco De Vita', year: 1990 },
    { name: 'Louis', artist: 'Franco De Vita', year: 1984 },
    { name: 'Me Va a Extrañar', artist: 'Ricardo Montaner', year: 1991 },
    { name: 'La Cima del Cielo', artist: 'Ricardo Montaner', year: 1988 },
    { name: 'Bésame', artist: 'Ricardo Montaner', year: 1987 },
    { name: 'Azul', artist: 'Cristian Castro', year: 2001 },
    { name: 'No Podrás', artist: 'Cristian Castro', year: 1999 },
    { name: 'Lloran las Rosas', artist: 'Cristian Castro', year: 1999 },
    { name: 'Olvídame y Pega la Vuelta', artist: 'Pimpinela', year: 1982 },
    { name: 'Simplemente Amigos', artist: 'Ana Gabriel', year: 1990 },
    { name: 'Ay Amor', artist: 'Ana Gabriel', year: 1987 },
    { name: 'Eternamente Bella', artist: 'Alejandra Guzmán', year: 1990 },
    { name: 'Hacer el Amor con Otro', artist: 'Alejandra Guzmán', year: 1990 },
    { name: 'Ni Una Sola Palabra', artist: 'Paulina Rubio', year: 2006 },
    { name: 'Y Yo Sigo Aquí', artist: 'Paulina Rubio', year: 2000 },
    { name: 'Mío', artist: 'Paulina Rubio', year: 1992 },
    { name: 'Bella Traición', artist: 'Belinda', year: 2007 },
    { name: 'Ángel', artist: 'Belinda', year: 2003 },
    { name: 'Sálvame', artist: 'RBD', year: 2005 },
    { name: 'Rebelde', artist: 'RBD', year: 2004 },
    { name: 'Sólo Quédate en Silencio', artist: 'RBD', year: 2004 },
    { name: 'Ave María', artist: 'David Bisbal', year: 2002 },
    { name: 'Bulería', artist: 'David Bisbal', year: 2004 },
    { name: 'Dígale', artist: 'David Bisbal', year: 2002 },
    { name: 'Caraluna', artist: 'Bacilos', year: 2002 },
    { name: 'Mi Primer Millón', artist: 'Bacilos', year: 2001 },
    { name: 'Tabaco y Chanel', artist: 'Bacilos', year: 2002 },
    { name: 'Te Mando Flores', artist: 'Fonseca', year: 2006 },
    { name: 'Eres Mi Sueño', artist: 'Fonseca', year: 2008 },
    { name: 'Tu Boca', artist: 'Cabas', year: 2001 },
    { name: 'La Cadena de Oro', artist: 'Cabas', year: 2003 },
    { name: 'Antes', artist: 'Obie Bermúdez', year: 2003 },
    { name: 'Perdón, Perdón', artist: 'Ha*Ash', year: 2014 },
    { name: 'Lo Aprendí de Ti', artist: 'Ha*Ash', year: 2011 },
    { name: 'Te Dejo en Libertad', artist: 'Ha*Ash', year: 2014 },
    { name: 'Hoy Ya Me Voy', artist: 'Kany García', year: 2007 },
    { name: 'Traicionera', artist: 'Sebastián Yatra', year: 2016 },
    { name: 'Un Año', artist: 'Sebastián Yatra', year: 2019 },
    { name: 'Sofia', artist: 'Álvaro Soler', year: 2016 },
    { name: 'El Mismo Sol', artist: 'Álvaro Soler', year: 2015 },
    { name: 'Mi Niña Bonita', artist: 'Chino & Nacho', year: 2010 },
    { name: 'Andas en Mi Cabeza', artist: 'Chino & Nacho', year: 2016 },
    { name: 'Déjala Que Vuelva', artist: 'Piso 21', year: 2017 },
    { name: 'Una Lady Como Tú', artist: 'Manuel Turizo', year: 2017 },
    { name: 'Nunca Es Suficiente', artist: 'Los Ángeles Azules', year: 2018 },
    { name: 'Hasta la Raíz', artist: 'Natalia Lafourcade', year: 2015 },
    { name: 'Tu Falta de Querer', artist: 'Mon Laferte', year: 2015 },
    { name: 'Adiós Amor', artist: 'Christian Nodal', year: 2017 },
    { name: 'Fuiste Tú', artist: 'Ricardo Arjona', year: 2011 },
    { name: 'Clandestino', artist: 'Manu Chao', year: 1998 },
    { name: 'Bongo Bong', artist: 'Manu Chao', year: 1998 },
    { name: 'La Gran Señora', artist: 'Jenni Rivera', year: 2009 },
    { name: 'De Contrabando', artist: 'Jenni Rivera', year: 2010 },
  ],
  'Reggaetón': [
    { name: 'Dura', artist: 'Daddy Yankee', year: 2018 },
    { name: 'Mayor Que Yo', artist: 'Baby Ranks', year: 2005 },
    { name: 'Pam Pam', artist: 'Wisin & Yandel', year: 2006 },
    { name: 'Algo Me Gusta de Ti', artist: 'Wisin & Yandel', year: 2012 },
    { name: 'Noche de Entierro', artist: 'Los Benjamins', year: 2006 },
    { name: 'Mayor Que Yo 3', artist: 'Luny Tunes', year: 2015 },
    { name: 'Mayor Que Yo 2', artist: 'Luny Tunes', year: 2010 },
    { name: 'Dile', artist: 'Don Omar', year: 2003 },
    { name: 'Danza Kuduro', artist: 'Lucenzo', year: 2010 },
    { name: 'Ven Báilalo', artist: 'Angel y Khriz', year: 2004 },
    { name: 'Na De Na', artist: 'Angel y Khriz', year: 2008 },
    { name: 'Carita de Ángel', artist: 'Erre XI', year: 2008 },
    { name: 'Nena', artist: 'Miguelito', year: 2006 },
    { name: 'Si No Le Contesto', artist: 'Plan B', year: 2010 },
    { name: 'Fanática Sensual', artist: 'Plan B', year: 2014 },
    { name: 'Candy', artist: 'Plan B', year: 2014 },
    { name: 'Me Niegas', artist: 'Baby Rasta & Gringo', year: 2013 },
    { name: 'Un Beso', artist: 'Aventura', year: 2005 },
    { name: 'Noche de Travesura', artist: 'Héctor El Father', year: 2005 },
    { name: 'Sola', artist: 'Héctor El Father', year: 2006 },
    { name: 'Déjale Caer To el Peso', artist: 'Héctor El Father', year: 2006 },
    { name: 'El Teléfono', artist: 'Héctor El Father & Wisin & Yandel', year: 2006 },
    { name: 'Caile', artist: 'Tito El Bambino', year: 2005 },
    { name: 'El Amor', artist: 'Tito El Bambino', year: 2009 },
    { name: 'Mi Cama Huele a Ti', artist: 'Tito El Bambino', year: 2009 },
    { name: 'Felina', artist: 'Hector & Tito', year: 2002 },
    { name: 'Baila Morena', artist: 'Hector & Tito', year: 2002 },
    { name: 'Métele Sazón', artist: 'Tego Calderón', year: 2003 },
    { name: 'Pa Que Retozen', artist: 'Tego Calderón', year: 2003 },
    { name: 'Punto y Aparte', artist: 'Tego Calderón', year: 2004 },
    { name: 'Zun Da Da', artist: 'Zion', year: 2007 },
    { name: 'Yo Voy', artist: 'Zion & Lennox', year: 2004 },
    { name: 'Otra Vez', artist: 'Zion & Lennox', year: 2016 },
    { name: 'Me Prefieres a Mí', artist: 'Arcángel', year: 2012 },
    { name: 'Hace Mucho Tiempo', artist: 'Arcángel', year: 2013 },
    { name: 'Me Acostumbré', artist: 'Arcángel', year: 2017 },
    { name: 'La Canción', artist: 'J Balvin & Bad Bunny', year: 2019 },
    { name: 'Qué Pretendes', artist: 'J Balvin & Bad Bunny', year: 2019 },
    { name: 'Ginza', artist: 'J Balvin', year: 2015 },
    { name: 'Loco Contigo', artist: 'DJ Snake, J Balvin & Tyga', year: 2019 },
    { name: 'Ella Quiere Beber', artist: 'Anuel AA', year: 2018 },
    { name: 'Adicto', artist: 'Tainy, Anuel AA & Ozuna', year: 2019 },
    { name: 'Baila Baila Baila', artist: 'Ozuna', year: 2019 },
    { name: 'Dile Que Tú Me Quieres', artist: 'Ozuna', year: 2016 },
    { name: 'Criminal', artist: 'Natti Natasha & Ozuna', year: 2017 },
    { name: 'Sin Pijama', artist: 'Becky G & Natti Natasha', year: 2018 },
    { name: 'Mayores', artist: 'Becky G', year: 2017 },
    { name: 'La Respuesta', artist: 'Becky G & Maluma', year: 2019 },
    { name: 'Soltera', artist: 'Lunay', year: 2019 },
    { name: 'A Solas', artist: 'Lunay', year: 2019 },
    { name: 'La Jeepeta', artist: 'Nio Garcia', year: 2020 },
    { name: 'Down', artist: 'Rakim & Ken-Y', year: 2006 },
    { name: 'Atrévete-Te-Te', artist: 'Calle 13', year: 2005 },
    { name: 'Latinoamérica', artist: 'Calle 13', year: 2010 },
    { name: 'Baile de los Pobres', artist: 'Calle 13', year: 2010 },
    { name: 'Quiero Bailar', artist: 'Ivy Queen', year: 2003 },
    { name: 'La Vida Es Así', artist: 'Ivy Queen', year: 2004 },
    { name: 'Te He Querido, Te He Llorado', artist: 'Ivy Queen', year: 2003 },
    { name: 'El Tiburón', artist: 'Alexis & Fido', year: 2005 },
    { name: 'Energía', artist: 'Alexis & Fido', year: 2005 },
    { name: 'Eso Ehh...!', artist: 'Alexis & Fido', year: 2005 },
    { name: 'Chulin Culin Chunfly', artist: 'Julio Voltio', year: 2005 },
    { name: 'Desahogo', artist: 'Vico C', year: 2003 },
    { name: 'Te Ves Buena', artist: 'El General', year: 1994 },
    { name: 'Muévelo', artist: 'El General', year: 1991 },
    { name: 'Papi Chulo... Te Traigo el Mmmm', artist: 'Lorna', year: 2003 },
    { name: 'Move Ya Body', artist: 'Nina Sky', year: 2004 },
    { name: 'Oye Mi Canto', artist: 'N.O.R.E.', year: 2004 },
    { name: 'Todo de Ti', artist: 'Rauw Alejandro', year: 2021 },
    { name: 'Fantasías', artist: 'Rauw Alejandro', year: 2020 },
    { name: 'Normal', artist: 'Feid', year: 2022 },
    { name: 'Ferxxo 100', artist: 'Feid', year: 2022 },
    { name: 'La Mejor Versión de Mí', artist: 'Natti Natasha', year: 2018 },
    { name: 'Encantadora', artist: 'Yandel', year: 2015 },
    { name: 'Prrrum', artist: 'Cosculluela', year: 2015 },
    { name: 'Esclava', artist: 'Bryant Myers', year: 2016 },
    { name: 'Krippy Kush', artist: 'Farruko', year: 2017 },
    { name: 'Chillax', artist: 'Farruko', year: 2014 },
    { name: 'Otro Trago', artist: 'Sech', year: 2019 },
    { name: 'La Curiosidad', artist: 'Myke Towers', year: 2020 },
    { name: 'Diosa', artist: 'Myke Towers', year: 2020 },
    { name: 'Te Regalo Amores', artist: 'Rakim & Ken-Y', year: 2006 },
    { name: 'Rebota', artist: 'Guaynaa', year: 2019 },
    { name: 'Con Altura', artist: 'Rosalía & J Balvin', year: 2019 },
    { name: 'Obsesión', artist: 'Aventura', year: 2002 },
    { name: 'Mi Corazoncito', artist: 'Aventura', year: 2007 },
    { name: 'Ayer la Vi', artist: 'Angel y Khriz', year: 2008 },
    { name: 'Permítame', artist: 'Tony Dize', year: 2008 },
    { name: 'El Doctorado', artist: 'Tony Dize', year: 2010 },
  ],
} satisfies Record<string, GenreSong[]>;
